/// <reference types="node" />
/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.15.6
 * source: srpc.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
import * as grpc_1 from "@grpc/grpc-js";
export declare namespace srpc {
    export class Empty extends pb_1.Message {
        #private;
        constructor(data?: any[] | {});
        static fromObject(data: {}): Empty;
        toObject(): {};
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Empty;
        serializeBinary(): Uint8Array;
        static deserializeBinary(bytes: Uint8Array): Empty;
    }
    export class Default extends pb_1.Message {
        #private;
        constructor(data?: any[] | {
            value?: string;
        });
        get value(): string;
        set value(value: string);
        static fromObject(data: {
            value?: string;
        }): Default;
        toObject(): {
            value?: string | undefined;
        };
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Default;
        serializeBinary(): Uint8Array;
        static deserializeBinary(bytes: Uint8Array): Default;
    }
    export class BucketSetRequest extends pb_1.Message {
        #private;
        constructor(data?: any[] | {
            name?: string;
            key?: string;
            value?: string;
        });
        get name(): string;
        set name(value: string);
        get key(): string;
        set key(value: string);
        get value(): string;
        set value(value: string);
        static fromObject(data: {
            name?: string;
            key?: string;
            value?: string;
        }): BucketSetRequest;
        toObject(): {
            name?: string | undefined;
            key?: string | undefined;
            value?: string | undefined;
        };
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): BucketSetRequest;
        serializeBinary(): Uint8Array;
        static deserializeBinary(bytes: Uint8Array): BucketSetRequest;
    }
    export class BucketWatchRequest extends pb_1.Message {
        #private;
        constructor(data?: any[] | {
            name?: string;
            key?: string;
            message?: string;
            error?: string;
            now?: string;
            echo?: string;
            plugin_id?: string;
        });
        get name(): string;
        set name(value: string);
        get key(): string;
        set key(value: string);
        get message(): string;
        set message(value: string);
        get error(): string;
        set error(value: string);
        get now(): string;
        set now(value: string);
        get echo(): string;
        set echo(value: string);
        get plugin_id(): string;
        set plugin_id(value: string);
        static fromObject(data: {
            name?: string;
            key?: string;
            message?: string;
            error?: string;
            now?: string;
            echo?: string;
            plugin_id?: string;
        }): BucketWatchRequest;
        toObject(): {
            name?: string | undefined;
            key?: string | undefined;
            message?: string | undefined;
            error?: string | undefined;
            now?: string | undefined;
            echo?: string | undefined;
            plugin_id?: string | undefined;
        };
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): BucketWatchRequest;
        serializeBinary(): Uint8Array;
        static deserializeBinary(bytes: Uint8Array): BucketWatchRequest;
    }
    export class BucketWatchResponse extends pb_1.Message {
        #private;
        constructor(data?: any[] | {
            echo?: string;
            old?: string;
            now?: string;
            key?: string;
        });
        get echo(): string;
        set echo(value: string);
        get old(): string;
        set old(value: string);
        get now(): string;
        set now(value: string);
        get key(): string;
        set key(value: string);
        static fromObject(data: {
            echo?: string;
            old?: string;
            now?: string;
            key?: string;
        }): BucketWatchResponse;
        toObject(): {
            echo?: string | undefined;
            old?: string | undefined;
            now?: string | undefined;
            key?: string | undefined;
        };
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): BucketWatchResponse;
        serializeBinary(): Uint8Array;
        static deserializeBinary(bytes: Uint8Array): BucketWatchResponse;
    }
    export class BucketSetResponse extends pb_1.Message {
        #private;
        constructor(data?: any[] | {
            changed?: boolean;
            message?: string;
        });
        get changed(): boolean;
        set changed(value: boolean);
        get message(): string;
        set message(value: string);
        static fromObject(data: {
            changed?: boolean;
            message?: string;
        }): BucketSetResponse;
        toObject(): {
            changed?: boolean | undefined;
            message?: string | undefined;
        };
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): BucketSetResponse;
        serializeBinary(): Uint8Array;
        static deserializeBinary(bytes: Uint8Array): BucketSetResponse;
    }
    export class BucketKeyRequest extends pb_1.Message {
        #private;
        constructor(data?: any[] | {
            name?: string;
            key?: string;
        });
        get name(): string;
        set name(value: string);
        get key(): string;
        set key(value: string);
        static fromObject(data: {
            name?: string;
            key?: string;
        }): BucketKeyRequest;
        toObject(): {
            name?: string | undefined;
            key?: string | undefined;
        };
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): BucketKeyRequest;
        serializeBinary(): Uint8Array;
        static deserializeBinary(bytes: Uint8Array): BucketKeyRequest;
    }
    export class BucketRequest extends pb_1.Message {
        #private;
        constructor(data?: any[] | {
            name?: string;
        });
        get name(): string;
        set name(value: string);
        static fromObject(data: {
            name?: string;
        }): BucketRequest;
        toObject(): {
            name?: string | undefined;
        };
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): BucketRequest;
        serializeBinary(): Uint8Array;
        static deserializeBinary(bytes: Uint8Array): BucketRequest;
    }
    export class BucketKeysResponse extends pb_1.Message {
        #private;
        constructor(data?: any[] | {
            keys?: string[];
        });
        get keys(): string[];
        set keys(value: string[]);
        static fromObject(data: {
            keys?: string[];
        }): BucketKeysResponse;
        toObject(): {
            keys?: string[] | undefined;
        };
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): BucketKeysResponse;
        serializeBinary(): Uint8Array;
        static deserializeBinary(bytes: Uint8Array): BucketKeysResponse;
    }
    export class LenResponse extends pb_1.Message {
        #private;
        constructor(data?: any[] | {
            length?: number;
        });
        get length(): number;
        set length(value: number);
        static fromObject(data: {
            length?: number;
        }): LenResponse;
        toObject(): {
            length?: number | undefined;
        };
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): LenResponse;
        serializeBinary(): Uint8Array;
        static deserializeBinary(bytes: Uint8Array): LenResponse;
    }
    export class BoolResponse extends pb_1.Message {
        #private;
        constructor(data?: any[] | {
            value?: boolean;
        });
        get value(): boolean;
        set value(value: boolean);
        static fromObject(data: {
            value?: boolean;
        }): BoolResponse;
        toObject(): {
            value?: boolean | undefined;
        };
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): BoolResponse;
        serializeBinary(): Uint8Array;
        static deserializeBinary(bytes: Uint8Array): BoolResponse;
    }
    export class BucketsResponse extends pb_1.Message {
        #private;
        constructor(data?: any[] | {
            buckets?: string[];
        });
        get buckets(): string[];
        set buckets(value: string[]);
        static fromObject(data: {
            buckets?: string[];
        }): BucketsResponse;
        toObject(): {
            buckets?: string[] | undefined;
        };
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): BucketsResponse;
        serializeBinary(): Uint8Array;
        static deserializeBinary(bytes: Uint8Array): BucketsResponse;
    }
    export class SenderRequest extends pb_1.Message {
        #private;
        constructor(data?: any[] | {
            uuid?: string;
        });
        get uuid(): string;
        set uuid(value: string);
        static fromObject(data: {
            uuid?: string;
        }): SenderRequest;
        toObject(): {
            uuid?: string | undefined;
        };
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): SenderRequest;
        serializeBinary(): Uint8Array;
        static deserializeBinary(bytes: Uint8Array): SenderRequest;
    }
    export class ReplyRequest extends pb_1.Message {
        #private;
        constructor(data?: any[] | {
            uuid?: string;
            content?: string;
        });
        get uuid(): string;
        set uuid(value: string);
        get content(): string;
        set content(value: string);
        static fromObject(data: {
            uuid?: string;
            content?: string;
        }): ReplyRequest;
        toObject(): {
            uuid?: string | undefined;
            content?: string | undefined;
        };
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): ReplyRequest;
        serializeBinary(): Uint8Array;
        static deserializeBinary(bytes: Uint8Array): ReplyRequest;
    }
    export class SenderContentRequest extends pb_1.Message {
        #private;
        constructor(data?: any[] | {
            uuid?: string;
            content?: string;
        });
        get uuid(): string;
        set uuid(value: string);
        get content(): string;
        set content(value: string);
        static fromObject(data: {
            uuid?: string;
            content?: string;
        }): SenderContentRequest;
        toObject(): {
            uuid?: string | undefined;
            content?: string | undefined;
        };
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): SenderContentRequest;
        serializeBinary(): Uint8Array;
        static deserializeBinary(bytes: Uint8Array): SenderContentRequest;
    }
    export class SenderListenResponse extends pb_1.Message {
        #private;
        constructor(data?: any[] | {
            echo?: string;
            uuid?: string;
        });
        get echo(): string;
        set echo(value: string);
        get uuid(): string;
        set uuid(value: string);
        static fromObject(data: {
            echo?: string;
            uuid?: string;
        }): SenderListenResponse;
        toObject(): {
            echo?: string | undefined;
            uuid?: string | undefined;
        };
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): SenderListenResponse;
        serializeBinary(): Uint8Array;
        static deserializeBinary(bytes: Uint8Array): SenderListenResponse;
    }
    export class SenderListenRequest extends pb_1.Message {
        #private;
        constructor(data?: any[] | {
            uuid?: string;
            rules?: string[];
            timeout?: number;
            listen_group?: boolean;
            listen_private?: boolean;
            require_admin?: boolean;
            allow_platforms?: string[];
            prohibit_platforms?: string[];
            allow_users?: string[];
            prohibit_users?: string[];
            allow_groups?: string[];
            prohibit_groups?: string[];
            persistent?: boolean;
            value?: string;
            plugin_id?: string;
        });
        get uuid(): string;
        set uuid(value: string);
        get rules(): string[];
        set rules(value: string[]);
        get timeout(): number;
        set timeout(value: number);
        get listen_group(): boolean;
        set listen_group(value: boolean);
        get listen_private(): boolean;
        set listen_private(value: boolean);
        get require_admin(): boolean;
        set require_admin(value: boolean);
        get allow_platforms(): string[];
        set allow_platforms(value: string[]);
        get prohibit_platforms(): string[];
        set prohibit_platforms(value: string[]);
        get allow_users(): string[];
        set allow_users(value: string[]);
        get prohibit_users(): string[];
        set prohibit_users(value: string[]);
        get allow_groups(): string[];
        set allow_groups(value: string[]);
        get prohibit_groups(): string[];
        set prohibit_groups(value: string[]);
        get persistent(): boolean;
        set persistent(value: boolean);
        get value(): string;
        set value(value: string);
        get plugin_id(): string;
        set plugin_id(value: string);
        static fromObject(data: {
            uuid?: string;
            rules?: string[];
            timeout?: number;
            listen_group?: boolean;
            listen_private?: boolean;
            require_admin?: boolean;
            allow_platforms?: string[];
            prohibit_platforms?: string[];
            allow_users?: string[];
            prohibit_users?: string[];
            allow_groups?: string[];
            prohibit_groups?: string[];
            persistent?: boolean;
            value?: string;
            plugin_id?: string;
        }): SenderListenRequest;
        toObject(): {
            uuid?: string | undefined;
            rules?: string[] | undefined;
            timeout?: number | undefined;
            listen_group?: boolean | undefined;
            listen_private?: boolean | undefined;
            require_admin?: boolean | undefined;
            allow_platforms?: string[] | undefined;
            prohibit_platforms?: string[] | undefined;
            allow_users?: string[] | undefined;
            prohibit_users?: string[] | undefined;
            allow_groups?: string[] | undefined;
            prohibit_groups?: string[] | undefined;
            persistent?: boolean | undefined;
            value?: string | undefined;
            plugin_id?: string | undefined;
        };
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): SenderListenRequest;
        serializeBinary(): Uint8Array;
        static deserializeBinary(bytes: Uint8Array): SenderListenRequest;
    }
    export class AdapterRegistRequest extends pb_1.Message {
        #private;
        constructor(data?: any[] | {
            platform?: string;
            bot_id?: string;
        });
        get platform(): string;
        set platform(value: string);
        get bot_id(): string;
        set bot_id(value: string);
        static fromObject(data: {
            platform?: string;
            bot_id?: string;
        }): AdapterRegistRequest;
        toObject(): {
            platform?: string | undefined;
            bot_id?: string | undefined;
        };
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): AdapterRegistRequest;
        serializeBinary(): Uint8Array;
        static deserializeBinary(bytes: Uint8Array): AdapterRegistRequest;
    }
    export class AdapterRequest extends pb_1.Message {
        #private;
        constructor(data?: any[] | {
            platform?: string;
            bot_id?: string;
            value?: string;
        });
        get platform(): string;
        set platform(value: string);
        get bot_id(): string;
        set bot_id(value: string);
        get value(): string;
        set value(value: string);
        static fromObject(data: {
            platform?: string;
            bot_id?: string;
            value?: string;
        }): AdapterRequest;
        toObject(): {
            platform?: string | undefined;
            bot_id?: string | undefined;
            value?: string | undefined;
        };
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): AdapterRequest;
        serializeBinary(): Uint8Array;
        static deserializeBinary(bytes: Uint8Array): AdapterRequest;
    }
    export class Any extends pb_1.Message {
        #private;
        constructor(data?: any[] | {
            type_url?: string;
            value?: Uint8Array;
        });
        get type_url(): string;
        set type_url(value: string);
        get value(): Uint8Array;
        set value(value: Uint8Array);
        static fromObject(data: {
            type_url?: string;
            value?: Uint8Array;
        }): Any;
        toObject(): {
            type_url?: string | undefined;
            value?: Uint8Array | undefined;
        };
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Any;
        serializeBinary(): Uint8Array;
        static deserializeBinary(bytes: Uint8Array): Any;
    }
    export class ConsoleRequest extends pb_1.Message {
        #private;
        constructor(data?: any[] | {
            type?: string;
            content?: string;
            plugin_id?: string;
        });
        get type(): string;
        set type(value: string);
        get content(): string;
        set content(value: string);
        get plugin_id(): string;
        set plugin_id(value: string);
        static fromObject(data: {
            type?: string;
            content?: string;
            plugin_id?: string;
        }): ConsoleRequest;
        toObject(): {
            type?: string | undefined;
            content?: string | undefined;
            plugin_id?: string | undefined;
        };
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): ConsoleRequest;
        serializeBinary(): Uint8Array;
        static deserializeBinary(bytes: Uint8Array): ConsoleRequest;
    }
    interface GrpcUnaryServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, metadata: grpc_1.Metadata, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
    }
    interface GrpcChunkServiceInterface<P, R> {
        (metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): grpc_1.ClientDuplexStream<P, R>;
        (options?: grpc_1.CallOptions): grpc_1.ClientDuplexStream<P, R>;
    }
    export abstract class UnimplementedSillyGirlServiceService {
        static definition: {
            BucketGet: {
                path: string;
                requestStream: boolean;
                responseStream: boolean;
                requestSerialize: (message: BucketKeyRequest) => Buffer;
                requestDeserialize: (bytes: Buffer) => BucketKeyRequest;
                responseSerialize: (message: Default) => Buffer;
                responseDeserialize: (bytes: Buffer) => Default;
            };
            BucketSet: {
                path: string;
                requestStream: boolean;
                responseStream: boolean;
                requestSerialize: (message: BucketSetRequest) => Buffer;
                requestDeserialize: (bytes: Buffer) => BucketSetRequest;
                responseSerialize: (message: BucketSetResponse) => Buffer;
                responseDeserialize: (bytes: Buffer) => BucketSetResponse;
            };
            BucketDelete: {
                path: string;
                requestStream: boolean;
                responseStream: boolean;
                requestSerialize: (message: BucketRequest) => Buffer;
                requestDeserialize: (bytes: Buffer) => BucketRequest;
                responseSerialize: (message: Empty) => Buffer;
                responseDeserialize: (bytes: Buffer) => Empty;
            };
            BucketKeys: {
                path: string;
                requestStream: boolean;
                responseStream: boolean;
                requestSerialize: (message: BucketRequest) => Buffer;
                requestDeserialize: (bytes: Buffer) => BucketRequest;
                responseSerialize: (message: BucketKeysResponse) => Buffer;
                responseDeserialize: (bytes: Buffer) => BucketKeysResponse;
            };
            BucketLen: {
                path: string;
                requestStream: boolean;
                responseStream: boolean;
                requestSerialize: (message: BucketRequest) => Buffer;
                requestDeserialize: (bytes: Buffer) => BucketRequest;
                responseSerialize: (message: LenResponse) => Buffer;
                responseDeserialize: (bytes: Buffer) => LenResponse;
            };
            BucketGetAll: {
                path: string;
                requestStream: boolean;
                responseStream: boolean;
                requestSerialize: (message: BucketRequest) => Buffer;
                requestDeserialize: (bytes: Buffer) => BucketRequest;
                responseSerialize: (message: Default) => Buffer;
                responseDeserialize: (bytes: Buffer) => Default;
            };
            BucketBuckets: {
                path: string;
                requestStream: boolean;
                responseStream: boolean;
                requestSerialize: (message: Empty) => Buffer;
                requestDeserialize: (bytes: Buffer) => Empty;
                responseSerialize: (message: BucketsResponse) => Buffer;
                responseDeserialize: (bytes: Buffer) => BucketsResponse;
            };
            BucketWatch: {
                path: string;
                requestStream: boolean;
                responseStream: boolean;
                requestSerialize: (message: BucketWatchRequest) => Buffer;
                requestDeserialize: (bytes: Buffer) => BucketWatchRequest;
                responseSerialize: (message: BucketWatchResponse) => Buffer;
                responseDeserialize: (bytes: Buffer) => BucketWatchResponse;
            };
            SenderGetUserId: {
                path: string;
                requestStream: boolean;
                responseStream: boolean;
                requestSerialize: (message: SenderRequest) => Buffer;
                requestDeserialize: (bytes: Buffer) => SenderRequest;
                responseSerialize: (message: Default) => Buffer;
                responseDeserialize: (bytes: Buffer) => Default;
            };
            SenderGetUserName: {
                path: string;
                requestStream: boolean;
                responseStream: boolean;
                requestSerialize: (message: SenderRequest) => Buffer;
                requestDeserialize: (bytes: Buffer) => SenderRequest;
                responseSerialize: (message: Default) => Buffer;
                responseDeserialize: (bytes: Buffer) => Default;
            };
            SenderGetChatId: {
                path: string;
                requestStream: boolean;
                responseStream: boolean;
                requestSerialize: (message: SenderRequest) => Buffer;
                requestDeserialize: (bytes: Buffer) => SenderRequest;
                responseSerialize: (message: Default) => Buffer;
                responseDeserialize: (bytes: Buffer) => Default;
            };
            SenderGetChatName: {
                path: string;
                requestStream: boolean;
                responseStream: boolean;
                requestSerialize: (message: SenderRequest) => Buffer;
                requestDeserialize: (bytes: Buffer) => SenderRequest;
                responseSerialize: (message: Default) => Buffer;
                responseDeserialize: (bytes: Buffer) => Default;
            };
            SenderGetMessageId: {
                path: string;
                requestStream: boolean;
                responseStream: boolean;
                requestSerialize: (message: SenderRequest) => Buffer;
                requestDeserialize: (bytes: Buffer) => SenderRequest;
                responseSerialize: (message: Default) => Buffer;
                responseDeserialize: (bytes: Buffer) => Default;
            };
            SenderIsAdmin: {
                path: string;
                requestStream: boolean;
                responseStream: boolean;
                requestSerialize: (message: SenderRequest) => Buffer;
                requestDeserialize: (bytes: Buffer) => SenderRequest;
                responseSerialize: (message: BoolResponse) => Buffer;
                responseDeserialize: (bytes: Buffer) => BoolResponse;
            };
            SenderGetPlatform: {
                path: string;
                requestStream: boolean;
                responseStream: boolean;
                requestSerialize: (message: SenderRequest) => Buffer;
                requestDeserialize: (bytes: Buffer) => SenderRequest;
                responseSerialize: (message: Default) => Buffer;
                responseDeserialize: (bytes: Buffer) => Default;
            };
            SenderGetBotId: {
                path: string;
                requestStream: boolean;
                responseStream: boolean;
                requestSerialize: (message: SenderRequest) => Buffer;
                requestDeserialize: (bytes: Buffer) => SenderRequest;
                responseSerialize: (message: Default) => Buffer;
                responseDeserialize: (bytes: Buffer) => Default;
            };
            SenderGetContent: {
                path: string;
                requestStream: boolean;
                responseStream: boolean;
                requestSerialize: (message: SenderRequest) => Buffer;
                requestDeserialize: (bytes: Buffer) => SenderRequest;
                responseSerialize: (message: Default) => Buffer;
                responseDeserialize: (bytes: Buffer) => Default;
            };
            SenderSetContent: {
                path: string;
                requestStream: boolean;
                responseStream: boolean;
                requestSerialize: (message: SenderContentRequest) => Buffer;
                requestDeserialize: (bytes: Buffer) => SenderContentRequest;
                responseSerialize: (message: Empty) => Buffer;
                responseDeserialize: (bytes: Buffer) => Empty;
            };
            SenderContinue: {
                path: string;
                requestStream: boolean;
                responseStream: boolean;
                requestSerialize: (message: SenderRequest) => Buffer;
                requestDeserialize: (bytes: Buffer) => SenderRequest;
                responseSerialize: (message: Empty) => Buffer;
                responseDeserialize: (bytes: Buffer) => Empty;
            };
            SenderListen: {
                path: string;
                requestStream: boolean;
                responseStream: boolean;
                requestSerialize: (message: SenderListenRequest) => Buffer;
                requestDeserialize: (bytes: Buffer) => SenderListenRequest;
                responseSerialize: (message: SenderListenResponse) => Buffer;
                responseDeserialize: (bytes: Buffer) => SenderListenResponse;
            };
            SenderEvent: {
                path: string;
                requestStream: boolean;
                responseStream: boolean;
                requestSerialize: (message: SenderRequest) => Buffer;
                requestDeserialize: (bytes: Buffer) => SenderRequest;
                responseSerialize: (message: Default) => Buffer;
                responseDeserialize: (bytes: Buffer) => Default;
            };
            SenderReply: {
                path: string;
                requestStream: boolean;
                responseStream: boolean;
                requestSerialize: (message: ReplyRequest) => Buffer;
                requestDeserialize: (bytes: Buffer) => ReplyRequest;
                responseSerialize: (message: Default) => Buffer;
                responseDeserialize: (bytes: Buffer) => Default;
            };
            SenderParam: {
                path: string;
                requestStream: boolean;
                responseStream: boolean;
                requestSerialize: (message: ReplyRequest) => Buffer;
                requestDeserialize: (bytes: Buffer) => ReplyRequest;
                responseSerialize: (message: Default) => Buffer;
                responseDeserialize: (bytes: Buffer) => Default;
            };
            SenderAction: {
                path: string;
                requestStream: boolean;
                responseStream: boolean;
                requestSerialize: (message: ReplyRequest) => Buffer;
                requestDeserialize: (bytes: Buffer) => ReplyRequest;
                responseSerialize: (message: Default) => Buffer;
                responseDeserialize: (bytes: Buffer) => Default;
            };
            SenderDestroy: {
                path: string;
                requestStream: boolean;
                responseStream: boolean;
                requestSerialize: (message: ReplyRequest) => Buffer;
                requestDeserialize: (bytes: Buffer) => ReplyRequest;
                responseSerialize: (message: Empty) => Buffer;
                responseDeserialize: (bytes: Buffer) => Empty;
            };
            AdapterRegist: {
                path: string;
                requestStream: boolean;
                responseStream: boolean;
                requestSerialize: (message: AdapterRegistRequest) => Buffer;
                requestDeserialize: (bytes: Buffer) => AdapterRegistRequest;
                responseSerialize: (message: Default) => Buffer;
                responseDeserialize: (bytes: Buffer) => Default;
            };
            AdapterReceive: {
                path: string;
                requestStream: boolean;
                responseStream: boolean;
                requestSerialize: (message: AdapterRequest) => Buffer;
                requestDeserialize: (bytes: Buffer) => AdapterRequest;
                responseSerialize: (message: Empty) => Buffer;
                responseDeserialize: (bytes: Buffer) => Empty;
            };
            AdapterPush: {
                path: string;
                requestStream: boolean;
                responseStream: boolean;
                requestSerialize: (message: AdapterRequest) => Buffer;
                requestDeserialize: (bytes: Buffer) => AdapterRequest;
                responseSerialize: (message: Default) => Buffer;
                responseDeserialize: (bytes: Buffer) => Default;
            };
            AdapterDestroy: {
                path: string;
                requestStream: boolean;
                responseStream: boolean;
                requestSerialize: (message: AdapterRequest) => Buffer;
                requestDeserialize: (bytes: Buffer) => AdapterRequest;
                responseSerialize: (message: Empty) => Buffer;
                responseDeserialize: (bytes: Buffer) => Empty;
            };
            AdapterSender: {
                path: string;
                requestStream: boolean;
                responseStream: boolean;
                requestSerialize: (message: AdapterRequest) => Buffer;
                requestDeserialize: (bytes: Buffer) => AdapterRequest;
                responseSerialize: (message: Default) => Buffer;
                responseDeserialize: (bytes: Buffer) => Default;
            };
            Console: {
                path: string;
                requestStream: boolean;
                responseStream: boolean;
                requestSerialize: (message: ConsoleRequest) => Buffer;
                requestDeserialize: (bytes: Buffer) => ConsoleRequest;
                responseSerialize: (message: Empty) => Buffer;
                responseDeserialize: (bytes: Buffer) => Empty;
            };
        };
        [method: string]: grpc_1.UntypedHandleCall;
        abstract BucketGet(call: grpc_1.ServerUnaryCall<BucketKeyRequest, Default>, callback: grpc_1.sendUnaryData<Default>): void;
        abstract BucketSet(call: grpc_1.ServerUnaryCall<BucketSetRequest, BucketSetResponse>, callback: grpc_1.sendUnaryData<BucketSetResponse>): void;
        abstract BucketDelete(call: grpc_1.ServerUnaryCall<BucketRequest, Empty>, callback: grpc_1.sendUnaryData<Empty>): void;
        abstract BucketKeys(call: grpc_1.ServerUnaryCall<BucketRequest, BucketKeysResponse>, callback: grpc_1.sendUnaryData<BucketKeysResponse>): void;
        abstract BucketLen(call: grpc_1.ServerUnaryCall<BucketRequest, LenResponse>, callback: grpc_1.sendUnaryData<LenResponse>): void;
        abstract BucketGetAll(call: grpc_1.ServerUnaryCall<BucketRequest, Default>, callback: grpc_1.sendUnaryData<Default>): void;
        abstract BucketBuckets(call: grpc_1.ServerUnaryCall<Empty, BucketsResponse>, callback: grpc_1.sendUnaryData<BucketsResponse>): void;
        abstract BucketWatch(call: grpc_1.ServerDuplexStream<BucketWatchRequest, BucketWatchResponse>): void;
        abstract SenderGetUserId(call: grpc_1.ServerUnaryCall<SenderRequest, Default>, callback: grpc_1.sendUnaryData<Default>): void;
        abstract SenderGetUserName(call: grpc_1.ServerUnaryCall<SenderRequest, Default>, callback: grpc_1.sendUnaryData<Default>): void;
        abstract SenderGetChatId(call: grpc_1.ServerUnaryCall<SenderRequest, Default>, callback: grpc_1.sendUnaryData<Default>): void;
        abstract SenderGetChatName(call: grpc_1.ServerUnaryCall<SenderRequest, Default>, callback: grpc_1.sendUnaryData<Default>): void;
        abstract SenderGetMessageId(call: grpc_1.ServerUnaryCall<SenderRequest, Default>, callback: grpc_1.sendUnaryData<Default>): void;
        abstract SenderIsAdmin(call: grpc_1.ServerUnaryCall<SenderRequest, BoolResponse>, callback: grpc_1.sendUnaryData<BoolResponse>): void;
        abstract SenderGetPlatform(call: grpc_1.ServerUnaryCall<SenderRequest, Default>, callback: grpc_1.sendUnaryData<Default>): void;
        abstract SenderGetBotId(call: grpc_1.ServerUnaryCall<SenderRequest, Default>, callback: grpc_1.sendUnaryData<Default>): void;
        abstract SenderGetContent(call: grpc_1.ServerUnaryCall<SenderRequest, Default>, callback: grpc_1.sendUnaryData<Default>): void;
        abstract SenderSetContent(call: grpc_1.ServerUnaryCall<SenderContentRequest, Empty>, callback: grpc_1.sendUnaryData<Empty>): void;
        abstract SenderContinue(call: grpc_1.ServerUnaryCall<SenderRequest, Empty>, callback: grpc_1.sendUnaryData<Empty>): void;
        abstract SenderListen(call: grpc_1.ServerDuplexStream<SenderListenRequest, SenderListenResponse>): void;
        abstract SenderEvent(call: grpc_1.ServerUnaryCall<SenderRequest, Default>, callback: grpc_1.sendUnaryData<Default>): void;
        abstract SenderReply(call: grpc_1.ServerUnaryCall<ReplyRequest, Default>, callback: grpc_1.sendUnaryData<Default>): void;
        abstract SenderParam(call: grpc_1.ServerUnaryCall<ReplyRequest, Default>, callback: grpc_1.sendUnaryData<Default>): void;
        abstract SenderAction(call: grpc_1.ServerUnaryCall<ReplyRequest, Default>, callback: grpc_1.sendUnaryData<Default>): void;
        abstract SenderDestroy(call: grpc_1.ServerUnaryCall<ReplyRequest, Empty>, callback: grpc_1.sendUnaryData<Empty>): void;
        abstract AdapterRegist(call: grpc_1.ServerDuplexStream<AdapterRegistRequest, Default>): void;
        abstract AdapterReceive(call: grpc_1.ServerUnaryCall<AdapterRequest, Empty>, callback: grpc_1.sendUnaryData<Empty>): void;
        abstract AdapterPush(call: grpc_1.ServerUnaryCall<AdapterRequest, Default>, callback: grpc_1.sendUnaryData<Default>): void;
        abstract AdapterDestroy(call: grpc_1.ServerUnaryCall<AdapterRequest, Empty>, callback: grpc_1.sendUnaryData<Empty>): void;
        abstract AdapterSender(call: grpc_1.ServerUnaryCall<AdapterRequest, Default>, callback: grpc_1.sendUnaryData<Default>): void;
        abstract Console(call: grpc_1.ServerUnaryCall<ConsoleRequest, Empty>, callback: grpc_1.sendUnaryData<Empty>): void;
    }
    const SillyGirlServiceClient_base: grpc_1.ServiceClientConstructor;
    export class SillyGirlServiceClient extends SillyGirlServiceClient_base {
        constructor(address: string, credentials: grpc_1.ChannelCredentials, options?: Partial<grpc_1.ChannelOptions>);
        BucketGet: GrpcUnaryServiceInterface<BucketKeyRequest, Default>;
        BucketSet: GrpcUnaryServiceInterface<BucketSetRequest, BucketSetResponse>;
        BucketDelete: GrpcUnaryServiceInterface<BucketRequest, Empty>;
        BucketKeys: GrpcUnaryServiceInterface<BucketRequest, BucketKeysResponse>;
        BucketLen: GrpcUnaryServiceInterface<BucketRequest, LenResponse>;
        BucketGetAll: GrpcUnaryServiceInterface<BucketRequest, Default>;
        BucketBuckets: GrpcUnaryServiceInterface<Empty, BucketsResponse>;
        BucketWatch: GrpcChunkServiceInterface<BucketWatchRequest, BucketWatchResponse>;
        SenderGetUserId: GrpcUnaryServiceInterface<SenderRequest, Default>;
        SenderGetUserName: GrpcUnaryServiceInterface<SenderRequest, Default>;
        SenderGetChatId: GrpcUnaryServiceInterface<SenderRequest, Default>;
        SenderGetChatName: GrpcUnaryServiceInterface<SenderRequest, Default>;
        SenderGetMessageId: GrpcUnaryServiceInterface<SenderRequest, Default>;
        SenderIsAdmin: GrpcUnaryServiceInterface<SenderRequest, BoolResponse>;
        SenderGetPlatform: GrpcUnaryServiceInterface<SenderRequest, Default>;
        SenderGetBotId: GrpcUnaryServiceInterface<SenderRequest, Default>;
        SenderGetContent: GrpcUnaryServiceInterface<SenderRequest, Default>;
        SenderSetContent: GrpcUnaryServiceInterface<SenderContentRequest, Empty>;
        SenderContinue: GrpcUnaryServiceInterface<SenderRequest, Empty>;
        SenderListen: GrpcChunkServiceInterface<SenderListenRequest, SenderListenResponse>;
        SenderEvent: GrpcUnaryServiceInterface<SenderRequest, Default>;
        SenderReply: GrpcUnaryServiceInterface<ReplyRequest, Default>;
        SenderParam: GrpcUnaryServiceInterface<ReplyRequest, Default>;
        SenderAction: GrpcUnaryServiceInterface<ReplyRequest, Default>;
        SenderDestroy: GrpcUnaryServiceInterface<ReplyRequest, Empty>;
        AdapterRegist: GrpcChunkServiceInterface<AdapterRegistRequest, Default>;
        AdapterReceive: GrpcUnaryServiceInterface<AdapterRequest, Empty>;
        AdapterPush: GrpcUnaryServiceInterface<AdapterRequest, Default>;
        AdapterDestroy: GrpcUnaryServiceInterface<AdapterRequest, Empty>;
        AdapterSender: GrpcUnaryServiceInterface<AdapterRequest, Default>;
        Console: GrpcUnaryServiceInterface<ConsoleRequest, Empty>;
    }
    export {};
}
