"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
var __classPrivateFieldGet = (this && this.__classPrivateFieldGet) || function (receiver, state, kind, f) {
    if (kind === "a" && !f) throw new TypeError("Private accessor was defined without a getter");
    if (typeof state === "function" ? receiver !== state || !f : !state.has(receiver)) throw new TypeError("Cannot read private member from an object whose class did not declare it");
    return kind === "m" ? f : kind === "a" ? f.call(receiver) : f ? f.value : state.get(receiver);
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.srpc = void 0;
/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.15.6
 * source: srpc.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
const pb_1 = __importStar(require("google-protobuf"));
const grpc_1 = __importStar(require("@grpc/grpc-js"));
var srpc;
(function (srpc) {
    var _Empty_one_of_decls, _Default_one_of_decls, _BucketSetRequest_one_of_decls, _BucketSetResponse_one_of_decls, _BucketKeyRequest_one_of_decls, _BucketRequest_one_of_decls, _BucketKeysResponse_one_of_decls, _LenResponse_one_of_decls, _BucketsResponse_one_of_decls, _SenderRequest_one_of_decls, _ReplyRequest_one_of_decls, _SenderContentRequest_one_of_decls, _SenderListenRequest_one_of_decls, _AdapterRegistRequest_one_of_decls, _AdapterRequest_one_of_decls;
    class Empty extends pb_1.Message {
        constructor(data) {
            super();
            _Empty_one_of_decls.set(this, []);
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], __classPrivateFieldGet(this, _Empty_one_of_decls, "f"));
            if (!Array.isArray(data) && typeof data == "object") { }
        }
        static fromObject(data) {
            const message = new Empty({});
            return message;
        }
        toObject() {
            const data = {};
            return data;
        }
        serialize(w) {
            const writer = w || new pb_1.BinaryWriter();
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes) {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new Empty();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary() {
            return this.serialize();
        }
        static deserializeBinary(bytes) {
            return Empty.deserialize(bytes);
        }
    }
    _Empty_one_of_decls = new WeakMap();
    srpc.Empty = Empty;
    class Default extends pb_1.Message {
        constructor(data) {
            super();
            _Default_one_of_decls.set(this, []);
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], __classPrivateFieldGet(this, _Default_one_of_decls, "f"));
            if (!Array.isArray(data) && typeof data == "object") {
                if ("value" in data && data.value != undefined) {
                    this.value = data.value;
                }
            }
        }
        get value() {
            return pb_1.Message.getFieldWithDefault(this, 1, "");
        }
        set value(value) {
            pb_1.Message.setField(this, 1, value);
        }
        static fromObject(data) {
            const message = new Default({});
            if (data.value != null) {
                message.value = data.value;
            }
            return message;
        }
        toObject() {
            const data = {};
            if (this.value != null) {
                data.value = this.value;
            }
            return data;
        }
        serialize(w) {
            const writer = w || new pb_1.BinaryWriter();
            if (this.value.length)
                writer.writeString(1, this.value);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes) {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new Default();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.value = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary() {
            return this.serialize();
        }
        static deserializeBinary(bytes) {
            return Default.deserialize(bytes);
        }
    }
    _Default_one_of_decls = new WeakMap();
    srpc.Default = Default;
    class BucketSetRequest extends pb_1.Message {
        constructor(data) {
            super();
            _BucketSetRequest_one_of_decls.set(this, []);
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], __classPrivateFieldGet(this, _BucketSetRequest_one_of_decls, "f"));
            if (!Array.isArray(data) && typeof data == "object") {
                if ("name" in data && data.name != undefined) {
                    this.name = data.name;
                }
                if ("key" in data && data.key != undefined) {
                    this.key = data.key;
                }
                if ("value" in data && data.value != undefined) {
                    this.value = data.value;
                }
            }
        }
        get name() {
            return pb_1.Message.getFieldWithDefault(this, 1, "");
        }
        set name(value) {
            pb_1.Message.setField(this, 1, value);
        }
        get key() {
            return pb_1.Message.getFieldWithDefault(this, 2, "");
        }
        set key(value) {
            pb_1.Message.setField(this, 2, value);
        }
        get value() {
            return pb_1.Message.getFieldWithDefault(this, 3, "");
        }
        set value(value) {
            pb_1.Message.setField(this, 3, value);
        }
        static fromObject(data) {
            const message = new BucketSetRequest({});
            if (data.name != null) {
                message.name = data.name;
            }
            if (data.key != null) {
                message.key = data.key;
            }
            if (data.value != null) {
                message.value = data.value;
            }
            return message;
        }
        toObject() {
            const data = {};
            if (this.name != null) {
                data.name = this.name;
            }
            if (this.key != null) {
                data.key = this.key;
            }
            if (this.value != null) {
                data.value = this.value;
            }
            return data;
        }
        serialize(w) {
            const writer = w || new pb_1.BinaryWriter();
            if (this.name.length)
                writer.writeString(1, this.name);
            if (this.key.length)
                writer.writeString(2, this.key);
            if (this.value.length)
                writer.writeString(3, this.value);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes) {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new BucketSetRequest();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.name = reader.readString();
                        break;
                    case 2:
                        message.key = reader.readString();
                        break;
                    case 3:
                        message.value = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary() {
            return this.serialize();
        }
        static deserializeBinary(bytes) {
            return BucketSetRequest.deserialize(bytes);
        }
    }
    _BucketSetRequest_one_of_decls = new WeakMap();
    srpc.BucketSetRequest = BucketSetRequest;
    class BucketSetResponse extends pb_1.Message {
        constructor(data) {
            super();
            _BucketSetResponse_one_of_decls.set(this, []);
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], __classPrivateFieldGet(this, _BucketSetResponse_one_of_decls, "f"));
            if (!Array.isArray(data) && typeof data == "object") {
                if ("changed" in data && data.changed != undefined) {
                    this.changed = data.changed;
                }
                if ("message" in data && data.message != undefined) {
                    this.message = data.message;
                }
            }
        }
        get changed() {
            return pb_1.Message.getFieldWithDefault(this, 1, false);
        }
        set changed(value) {
            pb_1.Message.setField(this, 1, value);
        }
        get message() {
            return pb_1.Message.getFieldWithDefault(this, 2, "");
        }
        set message(value) {
            pb_1.Message.setField(this, 2, value);
        }
        static fromObject(data) {
            const message = new BucketSetResponse({});
            if (data.changed != null) {
                message.changed = data.changed;
            }
            if (data.message != null) {
                message.message = data.message;
            }
            return message;
        }
        toObject() {
            const data = {};
            if (this.changed != null) {
                data.changed = this.changed;
            }
            if (this.message != null) {
                data.message = this.message;
            }
            return data;
        }
        serialize(w) {
            const writer = w || new pb_1.BinaryWriter();
            if (this.changed != false)
                writer.writeBool(1, this.changed);
            if (this.message.length)
                writer.writeString(2, this.message);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes) {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new BucketSetResponse();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.changed = reader.readBool();
                        break;
                    case 2:
                        message.message = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary() {
            return this.serialize();
        }
        static deserializeBinary(bytes) {
            return BucketSetResponse.deserialize(bytes);
        }
    }
    _BucketSetResponse_one_of_decls = new WeakMap();
    srpc.BucketSetResponse = BucketSetResponse;
    class BucketKeyRequest extends pb_1.Message {
        constructor(data) {
            super();
            _BucketKeyRequest_one_of_decls.set(this, []);
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], __classPrivateFieldGet(this, _BucketKeyRequest_one_of_decls, "f"));
            if (!Array.isArray(data) && typeof data == "object") {
                if ("name" in data && data.name != undefined) {
                    this.name = data.name;
                }
                if ("key" in data && data.key != undefined) {
                    this.key = data.key;
                }
            }
        }
        get name() {
            return pb_1.Message.getFieldWithDefault(this, 1, "");
        }
        set name(value) {
            pb_1.Message.setField(this, 1, value);
        }
        get key() {
            return pb_1.Message.getFieldWithDefault(this, 2, "");
        }
        set key(value) {
            pb_1.Message.setField(this, 2, value);
        }
        static fromObject(data) {
            const message = new BucketKeyRequest({});
            if (data.name != null) {
                message.name = data.name;
            }
            if (data.key != null) {
                message.key = data.key;
            }
            return message;
        }
        toObject() {
            const data = {};
            if (this.name != null) {
                data.name = this.name;
            }
            if (this.key != null) {
                data.key = this.key;
            }
            return data;
        }
        serialize(w) {
            const writer = w || new pb_1.BinaryWriter();
            if (this.name.length)
                writer.writeString(1, this.name);
            if (this.key.length)
                writer.writeString(2, this.key);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes) {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new BucketKeyRequest();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.name = reader.readString();
                        break;
                    case 2:
                        message.key = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary() {
            return this.serialize();
        }
        static deserializeBinary(bytes) {
            return BucketKeyRequest.deserialize(bytes);
        }
    }
    _BucketKeyRequest_one_of_decls = new WeakMap();
    srpc.BucketKeyRequest = BucketKeyRequest;
    class BucketRequest extends pb_1.Message {
        constructor(data) {
            super();
            _BucketRequest_one_of_decls.set(this, []);
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], __classPrivateFieldGet(this, _BucketRequest_one_of_decls, "f"));
            if (!Array.isArray(data) && typeof data == "object") {
                if ("name" in data && data.name != undefined) {
                    this.name = data.name;
                }
            }
        }
        get name() {
            return pb_1.Message.getFieldWithDefault(this, 1, "");
        }
        set name(value) {
            pb_1.Message.setField(this, 1, value);
        }
        static fromObject(data) {
            const message = new BucketRequest({});
            if (data.name != null) {
                message.name = data.name;
            }
            return message;
        }
        toObject() {
            const data = {};
            if (this.name != null) {
                data.name = this.name;
            }
            return data;
        }
        serialize(w) {
            const writer = w || new pb_1.BinaryWriter();
            if (this.name.length)
                writer.writeString(1, this.name);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes) {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new BucketRequest();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.name = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary() {
            return this.serialize();
        }
        static deserializeBinary(bytes) {
            return BucketRequest.deserialize(bytes);
        }
    }
    _BucketRequest_one_of_decls = new WeakMap();
    srpc.BucketRequest = BucketRequest;
    class BucketKeysResponse extends pb_1.Message {
        constructor(data) {
            super();
            _BucketKeysResponse_one_of_decls.set(this, []);
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [1], __classPrivateFieldGet(this, _BucketKeysResponse_one_of_decls, "f"));
            if (!Array.isArray(data) && typeof data == "object") {
                if ("keys" in data && data.keys != undefined) {
                    this.keys = data.keys;
                }
            }
        }
        get keys() {
            return pb_1.Message.getFieldWithDefault(this, 1, []);
        }
        set keys(value) {
            pb_1.Message.setField(this, 1, value);
        }
        static fromObject(data) {
            const message = new BucketKeysResponse({});
            if (data.keys != null) {
                message.keys = data.keys;
            }
            return message;
        }
        toObject() {
            const data = {};
            if (this.keys != null) {
                data.keys = this.keys;
            }
            return data;
        }
        serialize(w) {
            const writer = w || new pb_1.BinaryWriter();
            if (this.keys.length)
                writer.writeRepeatedString(1, this.keys);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes) {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new BucketKeysResponse();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        pb_1.Message.addToRepeatedField(message, 1, reader.readString());
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary() {
            return this.serialize();
        }
        static deserializeBinary(bytes) {
            return BucketKeysResponse.deserialize(bytes);
        }
    }
    _BucketKeysResponse_one_of_decls = new WeakMap();
    srpc.BucketKeysResponse = BucketKeysResponse;
    class LenResponse extends pb_1.Message {
        constructor(data) {
            super();
            _LenResponse_one_of_decls.set(this, []);
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], __classPrivateFieldGet(this, _LenResponse_one_of_decls, "f"));
            if (!Array.isArray(data) && typeof data == "object") {
                if ("length" in data && data.length != undefined) {
                    this.length = data.length;
                }
            }
        }
        get length() {
            return pb_1.Message.getFieldWithDefault(this, 1, 0);
        }
        set length(value) {
            pb_1.Message.setField(this, 1, value);
        }
        static fromObject(data) {
            const message = new LenResponse({});
            if (data.length != null) {
                message.length = data.length;
            }
            return message;
        }
        toObject() {
            const data = {};
            if (this.length != null) {
                data.length = this.length;
            }
            return data;
        }
        serialize(w) {
            const writer = w || new pb_1.BinaryWriter();
            if (this.length != 0)
                writer.writeInt32(1, this.length);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes) {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new LenResponse();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.length = reader.readInt32();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary() {
            return this.serialize();
        }
        static deserializeBinary(bytes) {
            return LenResponse.deserialize(bytes);
        }
    }
    _LenResponse_one_of_decls = new WeakMap();
    srpc.LenResponse = LenResponse;
    class BucketsResponse extends pb_1.Message {
        constructor(data) {
            super();
            _BucketsResponse_one_of_decls.set(this, []);
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [1], __classPrivateFieldGet(this, _BucketsResponse_one_of_decls, "f"));
            if (!Array.isArray(data) && typeof data == "object") {
                if ("buckets" in data && data.buckets != undefined) {
                    this.buckets = data.buckets;
                }
            }
        }
        get buckets() {
            return pb_1.Message.getFieldWithDefault(this, 1, []);
        }
        set buckets(value) {
            pb_1.Message.setField(this, 1, value);
        }
        static fromObject(data) {
            const message = new BucketsResponse({});
            if (data.buckets != null) {
                message.buckets = data.buckets;
            }
            return message;
        }
        toObject() {
            const data = {};
            if (this.buckets != null) {
                data.buckets = this.buckets;
            }
            return data;
        }
        serialize(w) {
            const writer = w || new pb_1.BinaryWriter();
            if (this.buckets.length)
                writer.writeRepeatedString(1, this.buckets);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes) {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new BucketsResponse();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        pb_1.Message.addToRepeatedField(message, 1, reader.readString());
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary() {
            return this.serialize();
        }
        static deserializeBinary(bytes) {
            return BucketsResponse.deserialize(bytes);
        }
    }
    _BucketsResponse_one_of_decls = new WeakMap();
    srpc.BucketsResponse = BucketsResponse;
    class SenderRequest extends pb_1.Message {
        constructor(data) {
            super();
            _SenderRequest_one_of_decls.set(this, []);
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], __classPrivateFieldGet(this, _SenderRequest_one_of_decls, "f"));
            if (!Array.isArray(data) && typeof data == "object") {
                if ("uuid" in data && data.uuid != undefined) {
                    this.uuid = data.uuid;
                }
            }
        }
        get uuid() {
            return pb_1.Message.getFieldWithDefault(this, 1, "");
        }
        set uuid(value) {
            pb_1.Message.setField(this, 1, value);
        }
        static fromObject(data) {
            const message = new SenderRequest({});
            if (data.uuid != null) {
                message.uuid = data.uuid;
            }
            return message;
        }
        toObject() {
            const data = {};
            if (this.uuid != null) {
                data.uuid = this.uuid;
            }
            return data;
        }
        serialize(w) {
            const writer = w || new pb_1.BinaryWriter();
            if (this.uuid.length)
                writer.writeString(1, this.uuid);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes) {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new SenderRequest();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.uuid = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary() {
            return this.serialize();
        }
        static deserializeBinary(bytes) {
            return SenderRequest.deserialize(bytes);
        }
    }
    _SenderRequest_one_of_decls = new WeakMap();
    srpc.SenderRequest = SenderRequest;
    class ReplyRequest extends pb_1.Message {
        constructor(data) {
            super();
            _ReplyRequest_one_of_decls.set(this, []);
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], __classPrivateFieldGet(this, _ReplyRequest_one_of_decls, "f"));
            if (!Array.isArray(data) && typeof data == "object") {
                if ("uuid" in data && data.uuid != undefined) {
                    this.uuid = data.uuid;
                }
                if ("content" in data && data.content != undefined) {
                    this.content = data.content;
                }
            }
        }
        get uuid() {
            return pb_1.Message.getFieldWithDefault(this, 1, "");
        }
        set uuid(value) {
            pb_1.Message.setField(this, 1, value);
        }
        get content() {
            return pb_1.Message.getFieldWithDefault(this, 2, "");
        }
        set content(value) {
            pb_1.Message.setField(this, 2, value);
        }
        static fromObject(data) {
            const message = new ReplyRequest({});
            if (data.uuid != null) {
                message.uuid = data.uuid;
            }
            if (data.content != null) {
                message.content = data.content;
            }
            return message;
        }
        toObject() {
            const data = {};
            if (this.uuid != null) {
                data.uuid = this.uuid;
            }
            if (this.content != null) {
                data.content = this.content;
            }
            return data;
        }
        serialize(w) {
            const writer = w || new pb_1.BinaryWriter();
            if (this.uuid.length)
                writer.writeString(1, this.uuid);
            if (this.content.length)
                writer.writeString(2, this.content);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes) {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new ReplyRequest();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.uuid = reader.readString();
                        break;
                    case 2:
                        message.content = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary() {
            return this.serialize();
        }
        static deserializeBinary(bytes) {
            return ReplyRequest.deserialize(bytes);
        }
    }
    _ReplyRequest_one_of_decls = new WeakMap();
    srpc.ReplyRequest = ReplyRequest;
    class SenderContentRequest extends pb_1.Message {
        constructor(data) {
            super();
            _SenderContentRequest_one_of_decls.set(this, []);
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], __classPrivateFieldGet(this, _SenderContentRequest_one_of_decls, "f"));
            if (!Array.isArray(data) && typeof data == "object") {
                if ("uuid" in data && data.uuid != undefined) {
                    this.uuid = data.uuid;
                }
                if ("content" in data && data.content != undefined) {
                    this.content = data.content;
                }
            }
        }
        get uuid() {
            return pb_1.Message.getFieldWithDefault(this, 1, "");
        }
        set uuid(value) {
            pb_1.Message.setField(this, 1, value);
        }
        get content() {
            return pb_1.Message.getFieldWithDefault(this, 2, "");
        }
        set content(value) {
            pb_1.Message.setField(this, 2, value);
        }
        static fromObject(data) {
            const message = new SenderContentRequest({});
            if (data.uuid != null) {
                message.uuid = data.uuid;
            }
            if (data.content != null) {
                message.content = data.content;
            }
            return message;
        }
        toObject() {
            const data = {};
            if (this.uuid != null) {
                data.uuid = this.uuid;
            }
            if (this.content != null) {
                data.content = this.content;
            }
            return data;
        }
        serialize(w) {
            const writer = w || new pb_1.BinaryWriter();
            if (this.uuid.length)
                writer.writeString(1, this.uuid);
            if (this.content.length)
                writer.writeString(2, this.content);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes) {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new SenderContentRequest();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.uuid = reader.readString();
                        break;
                    case 2:
                        message.content = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary() {
            return this.serialize();
        }
        static deserializeBinary(bytes) {
            return SenderContentRequest.deserialize(bytes);
        }
    }
    _SenderContentRequest_one_of_decls = new WeakMap();
    srpc.SenderContentRequest = SenderContentRequest;
    class SenderListenRequest extends pb_1.Message {
        constructor(data) {
            super();
            _SenderListenRequest_one_of_decls.set(this, []);
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [2, 7, 8, 9, 10, 11, 12], __classPrivateFieldGet(this, _SenderListenRequest_one_of_decls, "f"));
            if (!Array.isArray(data) && typeof data == "object") {
                if ("uuid" in data && data.uuid != undefined) {
                    this.uuid = data.uuid;
                }
                if ("rules" in data && data.rules != undefined) {
                    this.rules = data.rules;
                }
                if ("timeout" in data && data.timeout != undefined) {
                    this.timeout = data.timeout;
                }
                if ("listen_group" in data && data.listen_group != undefined) {
                    this.listen_group = data.listen_group;
                }
                if ("listen_private" in data && data.listen_private != undefined) {
                    this.listen_private = data.listen_private;
                }
                if ("require_admin" in data && data.require_admin != undefined) {
                    this.require_admin = data.require_admin;
                }
                if ("allow_platforms" in data && data.allow_platforms != undefined) {
                    this.allow_platforms = data.allow_platforms;
                }
                if ("prohibit_platforms" in data && data.prohibit_platforms != undefined) {
                    this.prohibit_platforms = data.prohibit_platforms;
                }
                if ("allow_users" in data && data.allow_users != undefined) {
                    this.allow_users = data.allow_users;
                }
                if ("prohibit_users" in data && data.prohibit_users != undefined) {
                    this.prohibit_users = data.prohibit_users;
                }
                if ("allow_groups" in data && data.allow_groups != undefined) {
                    this.allow_groups = data.allow_groups;
                }
                if ("prohibit_groups" in data && data.prohibit_groups != undefined) {
                    this.prohibit_groups = data.prohibit_groups;
                }
            }
        }
        get uuid() {
            return pb_1.Message.getFieldWithDefault(this, 1, "");
        }
        set uuid(value) {
            pb_1.Message.setField(this, 1, value);
        }
        get rules() {
            return pb_1.Message.getFieldWithDefault(this, 2, []);
        }
        set rules(value) {
            pb_1.Message.setField(this, 2, value);
        }
        get timeout() {
            return pb_1.Message.getFieldWithDefault(this, 3, 0);
        }
        set timeout(value) {
            pb_1.Message.setField(this, 3, value);
        }
        get listen_group() {
            return pb_1.Message.getFieldWithDefault(this, 4, false);
        }
        set listen_group(value) {
            pb_1.Message.setField(this, 4, value);
        }
        get listen_private() {
            return pb_1.Message.getFieldWithDefault(this, 5, false);
        }
        set listen_private(value) {
            pb_1.Message.setField(this, 5, value);
        }
        get require_admin() {
            return pb_1.Message.getFieldWithDefault(this, 6, false);
        }
        set require_admin(value) {
            pb_1.Message.setField(this, 6, value);
        }
        get allow_platforms() {
            return pb_1.Message.getFieldWithDefault(this, 7, []);
        }
        set allow_platforms(value) {
            pb_1.Message.setField(this, 7, value);
        }
        get prohibit_platforms() {
            return pb_1.Message.getFieldWithDefault(this, 8, []);
        }
        set prohibit_platforms(value) {
            pb_1.Message.setField(this, 8, value);
        }
        get allow_users() {
            return pb_1.Message.getFieldWithDefault(this, 9, []);
        }
        set allow_users(value) {
            pb_1.Message.setField(this, 9, value);
        }
        get prohibit_users() {
            return pb_1.Message.getFieldWithDefault(this, 10, []);
        }
        set prohibit_users(value) {
            pb_1.Message.setField(this, 10, value);
        }
        get allow_groups() {
            return pb_1.Message.getFieldWithDefault(this, 11, []);
        }
        set allow_groups(value) {
            pb_1.Message.setField(this, 11, value);
        }
        get prohibit_groups() {
            return pb_1.Message.getFieldWithDefault(this, 12, []);
        }
        set prohibit_groups(value) {
            pb_1.Message.setField(this, 12, value);
        }
        static fromObject(data) {
            const message = new SenderListenRequest({});
            if (data.uuid != null) {
                message.uuid = data.uuid;
            }
            if (data.rules != null) {
                message.rules = data.rules;
            }
            if (data.timeout != null) {
                message.timeout = data.timeout;
            }
            if (data.listen_group != null) {
                message.listen_group = data.listen_group;
            }
            if (data.listen_private != null) {
                message.listen_private = data.listen_private;
            }
            if (data.require_admin != null) {
                message.require_admin = data.require_admin;
            }
            if (data.allow_platforms != null) {
                message.allow_platforms = data.allow_platforms;
            }
            if (data.prohibit_platforms != null) {
                message.prohibit_platforms = data.prohibit_platforms;
            }
            if (data.allow_users != null) {
                message.allow_users = data.allow_users;
            }
            if (data.prohibit_users != null) {
                message.prohibit_users = data.prohibit_users;
            }
            if (data.allow_groups != null) {
                message.allow_groups = data.allow_groups;
            }
            if (data.prohibit_groups != null) {
                message.prohibit_groups = data.prohibit_groups;
            }
            return message;
        }
        toObject() {
            const data = {};
            if (this.uuid != null) {
                data.uuid = this.uuid;
            }
            if (this.rules != null) {
                data.rules = this.rules;
            }
            if (this.timeout != null) {
                data.timeout = this.timeout;
            }
            if (this.listen_group != null) {
                data.listen_group = this.listen_group;
            }
            if (this.listen_private != null) {
                data.listen_private = this.listen_private;
            }
            if (this.require_admin != null) {
                data.require_admin = this.require_admin;
            }
            if (this.allow_platforms != null) {
                data.allow_platforms = this.allow_platforms;
            }
            if (this.prohibit_platforms != null) {
                data.prohibit_platforms = this.prohibit_platforms;
            }
            if (this.allow_users != null) {
                data.allow_users = this.allow_users;
            }
            if (this.prohibit_users != null) {
                data.prohibit_users = this.prohibit_users;
            }
            if (this.allow_groups != null) {
                data.allow_groups = this.allow_groups;
            }
            if (this.prohibit_groups != null) {
                data.prohibit_groups = this.prohibit_groups;
            }
            return data;
        }
        serialize(w) {
            const writer = w || new pb_1.BinaryWriter();
            if (this.uuid.length)
                writer.writeString(1, this.uuid);
            if (this.rules.length)
                writer.writeRepeatedString(2, this.rules);
            if (this.timeout != 0)
                writer.writeInt32(3, this.timeout);
            if (this.listen_group != false)
                writer.writeBool(4, this.listen_group);
            if (this.listen_private != false)
                writer.writeBool(5, this.listen_private);
            if (this.require_admin != false)
                writer.writeBool(6, this.require_admin);
            if (this.allow_platforms.length)
                writer.writeRepeatedString(7, this.allow_platforms);
            if (this.prohibit_platforms.length)
                writer.writeRepeatedString(8, this.prohibit_platforms);
            if (this.allow_users.length)
                writer.writeRepeatedString(9, this.allow_users);
            if (this.prohibit_users.length)
                writer.writeRepeatedString(10, this.prohibit_users);
            if (this.allow_groups.length)
                writer.writeRepeatedString(11, this.allow_groups);
            if (this.prohibit_groups.length)
                writer.writeRepeatedString(12, this.prohibit_groups);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes) {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new SenderListenRequest();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.uuid = reader.readString();
                        break;
                    case 2:
                        pb_1.Message.addToRepeatedField(message, 2, reader.readString());
                        break;
                    case 3:
                        message.timeout = reader.readInt32();
                        break;
                    case 4:
                        message.listen_group = reader.readBool();
                        break;
                    case 5:
                        message.listen_private = reader.readBool();
                        break;
                    case 6:
                        message.require_admin = reader.readBool();
                        break;
                    case 7:
                        pb_1.Message.addToRepeatedField(message, 7, reader.readString());
                        break;
                    case 8:
                        pb_1.Message.addToRepeatedField(message, 8, reader.readString());
                        break;
                    case 9:
                        pb_1.Message.addToRepeatedField(message, 9, reader.readString());
                        break;
                    case 10:
                        pb_1.Message.addToRepeatedField(message, 10, reader.readString());
                        break;
                    case 11:
                        pb_1.Message.addToRepeatedField(message, 11, reader.readString());
                        break;
                    case 12:
                        pb_1.Message.addToRepeatedField(message, 12, reader.readString());
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary() {
            return this.serialize();
        }
        static deserializeBinary(bytes) {
            return SenderListenRequest.deserialize(bytes);
        }
    }
    _SenderListenRequest_one_of_decls = new WeakMap();
    srpc.SenderListenRequest = SenderListenRequest;
    class AdapterRegistRequest extends pb_1.Message {
        constructor(data) {
            super();
            _AdapterRegistRequest_one_of_decls.set(this, []);
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], __classPrivateFieldGet(this, _AdapterRegistRequest_one_of_decls, "f"));
            if (!Array.isArray(data) && typeof data == "object") {
                if ("platform" in data && data.platform != undefined) {
                    this.platform = data.platform;
                }
                if ("bot_id" in data && data.bot_id != undefined) {
                    this.bot_id = data.bot_id;
                }
            }
        }
        get platform() {
            return pb_1.Message.getFieldWithDefault(this, 1, "");
        }
        set platform(value) {
            pb_1.Message.setField(this, 1, value);
        }
        get bot_id() {
            return pb_1.Message.getFieldWithDefault(this, 2, "");
        }
        set bot_id(value) {
            pb_1.Message.setField(this, 2, value);
        }
        static fromObject(data) {
            const message = new AdapterRegistRequest({});
            if (data.platform != null) {
                message.platform = data.platform;
            }
            if (data.bot_id != null) {
                message.bot_id = data.bot_id;
            }
            return message;
        }
        toObject() {
            const data = {};
            if (this.platform != null) {
                data.platform = this.platform;
            }
            if (this.bot_id != null) {
                data.bot_id = this.bot_id;
            }
            return data;
        }
        serialize(w) {
            const writer = w || new pb_1.BinaryWriter();
            if (this.platform.length)
                writer.writeString(1, this.platform);
            if (this.bot_id.length)
                writer.writeString(2, this.bot_id);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes) {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new AdapterRegistRequest();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.platform = reader.readString();
                        break;
                    case 2:
                        message.bot_id = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary() {
            return this.serialize();
        }
        static deserializeBinary(bytes) {
            return AdapterRegistRequest.deserialize(bytes);
        }
    }
    _AdapterRegistRequest_one_of_decls = new WeakMap();
    srpc.AdapterRegistRequest = AdapterRegistRequest;
    class AdapterRequest extends pb_1.Message {
        constructor(data) {
            super();
            _AdapterRequest_one_of_decls.set(this, []);
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], __classPrivateFieldGet(this, _AdapterRequest_one_of_decls, "f"));
            if (!Array.isArray(data) && typeof data == "object") {
                if ("platform" in data && data.platform != undefined) {
                    this.platform = data.platform;
                }
                if ("bot_id" in data && data.bot_id != undefined) {
                    this.bot_id = data.bot_id;
                }
                if ("value" in data && data.value != undefined) {
                    this.value = data.value;
                }
            }
        }
        get platform() {
            return pb_1.Message.getFieldWithDefault(this, 1, "");
        }
        set platform(value) {
            pb_1.Message.setField(this, 1, value);
        }
        get bot_id() {
            return pb_1.Message.getFieldWithDefault(this, 2, "");
        }
        set bot_id(value) {
            pb_1.Message.setField(this, 2, value);
        }
        get value() {
            return pb_1.Message.getFieldWithDefault(this, 3, "");
        }
        set value(value) {
            pb_1.Message.setField(this, 3, value);
        }
        static fromObject(data) {
            const message = new AdapterRequest({});
            if (data.platform != null) {
                message.platform = data.platform;
            }
            if (data.bot_id != null) {
                message.bot_id = data.bot_id;
            }
            if (data.value != null) {
                message.value = data.value;
            }
            return message;
        }
        toObject() {
            const data = {};
            if (this.platform != null) {
                data.platform = this.platform;
            }
            if (this.bot_id != null) {
                data.bot_id = this.bot_id;
            }
            if (this.value != null) {
                data.value = this.value;
            }
            return data;
        }
        serialize(w) {
            const writer = w || new pb_1.BinaryWriter();
            if (this.platform.length)
                writer.writeString(1, this.platform);
            if (this.bot_id.length)
                writer.writeString(2, this.bot_id);
            if (this.value.length)
                writer.writeString(3, this.value);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes) {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new AdapterRequest();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.platform = reader.readString();
                        break;
                    case 2:
                        message.bot_id = reader.readString();
                        break;
                    case 3:
                        message.value = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary() {
            return this.serialize();
        }
        static deserializeBinary(bytes) {
            return AdapterRequest.deserialize(bytes);
        }
    }
    _AdapterRequest_one_of_decls = new WeakMap();
    srpc.AdapterRequest = AdapterRequest;
    class UnimplementedSillyGirlServiceService {
    }
    UnimplementedSillyGirlServiceService.definition = {
        BucketGet: {
            path: "/srpc.SillyGirlService/BucketGet",
            requestStream: false,
            responseStream: false,
            requestSerialize: (message) => Buffer.from(message.serialize()),
            requestDeserialize: (bytes) => BucketKeyRequest.deserialize(new Uint8Array(bytes)),
            responseSerialize: (message) => Buffer.from(message.serialize()),
            responseDeserialize: (bytes) => Default.deserialize(new Uint8Array(bytes))
        },
        BucketSet: {
            path: "/srpc.SillyGirlService/BucketSet",
            requestStream: false,
            responseStream: false,
            requestSerialize: (message) => Buffer.from(message.serialize()),
            requestDeserialize: (bytes) => BucketSetRequest.deserialize(new Uint8Array(bytes)),
            responseSerialize: (message) => Buffer.from(message.serialize()),
            responseDeserialize: (bytes) => BucketSetResponse.deserialize(new Uint8Array(bytes))
        },
        BucketDelete: {
            path: "/srpc.SillyGirlService/BucketDelete",
            requestStream: false,
            responseStream: false,
            requestSerialize: (message) => Buffer.from(message.serialize()),
            requestDeserialize: (bytes) => BucketRequest.deserialize(new Uint8Array(bytes)),
            responseSerialize: (message) => Buffer.from(message.serialize()),
            responseDeserialize: (bytes) => Empty.deserialize(new Uint8Array(bytes))
        },
        BucketKeys: {
            path: "/srpc.SillyGirlService/BucketKeys",
            requestStream: false,
            responseStream: false,
            requestSerialize: (message) => Buffer.from(message.serialize()),
            requestDeserialize: (bytes) => BucketRequest.deserialize(new Uint8Array(bytes)),
            responseSerialize: (message) => Buffer.from(message.serialize()),
            responseDeserialize: (bytes) => BucketKeysResponse.deserialize(new Uint8Array(bytes))
        },
        BucketLen: {
            path: "/srpc.SillyGirlService/BucketLen",
            requestStream: false,
            responseStream: false,
            requestSerialize: (message) => Buffer.from(message.serialize()),
            requestDeserialize: (bytes) => BucketRequest.deserialize(new Uint8Array(bytes)),
            responseSerialize: (message) => Buffer.from(message.serialize()),
            responseDeserialize: (bytes) => LenResponse.deserialize(new Uint8Array(bytes))
        },
        BucketGetAll: {
            path: "/srpc.SillyGirlService/BucketGetAll",
            requestStream: false,
            responseStream: false,
            requestSerialize: (message) => Buffer.from(message.serialize()),
            requestDeserialize: (bytes) => BucketRequest.deserialize(new Uint8Array(bytes)),
            responseSerialize: (message) => Buffer.from(message.serialize()),
            responseDeserialize: (bytes) => Default.deserialize(new Uint8Array(bytes))
        },
        BucketBuckets: {
            path: "/srpc.SillyGirlService/BucketBuckets",
            requestStream: false,
            responseStream: false,
            requestSerialize: (message) => Buffer.from(message.serialize()),
            requestDeserialize: (bytes) => Empty.deserialize(new Uint8Array(bytes)),
            responseSerialize: (message) => Buffer.from(message.serialize()),
            responseDeserialize: (bytes) => BucketsResponse.deserialize(new Uint8Array(bytes))
        },
        SenderGetUserId: {
            path: "/srpc.SillyGirlService/SenderGetUserId",
            requestStream: false,
            responseStream: false,
            requestSerialize: (message) => Buffer.from(message.serialize()),
            requestDeserialize: (bytes) => SenderRequest.deserialize(new Uint8Array(bytes)),
            responseSerialize: (message) => Buffer.from(message.serialize()),
            responseDeserialize: (bytes) => Default.deserialize(new Uint8Array(bytes))
        },
        SenderGetUserName: {
            path: "/srpc.SillyGirlService/SenderGetUserName",
            requestStream: false,
            responseStream: false,
            requestSerialize: (message) => Buffer.from(message.serialize()),
            requestDeserialize: (bytes) => SenderRequest.deserialize(new Uint8Array(bytes)),
            responseSerialize: (message) => Buffer.from(message.serialize()),
            responseDeserialize: (bytes) => Default.deserialize(new Uint8Array(bytes))
        },
        SenderGetChatId: {
            path: "/srpc.SillyGirlService/SenderGetChatId",
            requestStream: false,
            responseStream: false,
            requestSerialize: (message) => Buffer.from(message.serialize()),
            requestDeserialize: (bytes) => SenderRequest.deserialize(new Uint8Array(bytes)),
            responseSerialize: (message) => Buffer.from(message.serialize()),
            responseDeserialize: (bytes) => Default.deserialize(new Uint8Array(bytes))
        },
        SenderGetChatName: {
            path: "/srpc.SillyGirlService/SenderGetChatName",
            requestStream: false,
            responseStream: false,
            requestSerialize: (message) => Buffer.from(message.serialize()),
            requestDeserialize: (bytes) => SenderRequest.deserialize(new Uint8Array(bytes)),
            responseSerialize: (message) => Buffer.from(message.serialize()),
            responseDeserialize: (bytes) => Default.deserialize(new Uint8Array(bytes))
        },
        SenderGetMessageId: {
            path: "/srpc.SillyGirlService/SenderGetMessageId",
            requestStream: false,
            responseStream: false,
            requestSerialize: (message) => Buffer.from(message.serialize()),
            requestDeserialize: (bytes) => SenderRequest.deserialize(new Uint8Array(bytes)),
            responseSerialize: (message) => Buffer.from(message.serialize()),
            responseDeserialize: (bytes) => Default.deserialize(new Uint8Array(bytes))
        },
        SenderGetPlatform: {
            path: "/srpc.SillyGirlService/SenderGetPlatform",
            requestStream: false,
            responseStream: false,
            requestSerialize: (message) => Buffer.from(message.serialize()),
            requestDeserialize: (bytes) => SenderRequest.deserialize(new Uint8Array(bytes)),
            responseSerialize: (message) => Buffer.from(message.serialize()),
            responseDeserialize: (bytes) => Default.deserialize(new Uint8Array(bytes))
        },
        SenderGetBotId: {
            path: "/srpc.SillyGirlService/SenderGetBotId",
            requestStream: false,
            responseStream: false,
            requestSerialize: (message) => Buffer.from(message.serialize()),
            requestDeserialize: (bytes) => SenderRequest.deserialize(new Uint8Array(bytes)),
            responseSerialize: (message) => Buffer.from(message.serialize()),
            responseDeserialize: (bytes) => Default.deserialize(new Uint8Array(bytes))
        },
        SenderGetContent: {
            path: "/srpc.SillyGirlService/SenderGetContent",
            requestStream: false,
            responseStream: false,
            requestSerialize: (message) => Buffer.from(message.serialize()),
            requestDeserialize: (bytes) => SenderRequest.deserialize(new Uint8Array(bytes)),
            responseSerialize: (message) => Buffer.from(message.serialize()),
            responseDeserialize: (bytes) => Default.deserialize(new Uint8Array(bytes))
        },
        SenderSetContent: {
            path: "/srpc.SillyGirlService/SenderSetContent",
            requestStream: false,
            responseStream: false,
            requestSerialize: (message) => Buffer.from(message.serialize()),
            requestDeserialize: (bytes) => SenderContentRequest.deserialize(new Uint8Array(bytes)),
            responseSerialize: (message) => Buffer.from(message.serialize()),
            responseDeserialize: (bytes) => Empty.deserialize(new Uint8Array(bytes))
        },
        SenderContinue: {
            path: "/srpc.SillyGirlService/SenderContinue",
            requestStream: false,
            responseStream: false,
            requestSerialize: (message) => Buffer.from(message.serialize()),
            requestDeserialize: (bytes) => SenderRequest.deserialize(new Uint8Array(bytes)),
            responseSerialize: (message) => Buffer.from(message.serialize()),
            responseDeserialize: (bytes) => Empty.deserialize(new Uint8Array(bytes))
        },
        SenderListen: {
            path: "/srpc.SillyGirlService/SenderListen",
            requestStream: false,
            responseStream: false,
            requestSerialize: (message) => Buffer.from(message.serialize()),
            requestDeserialize: (bytes) => SenderListenRequest.deserialize(new Uint8Array(bytes)),
            responseSerialize: (message) => Buffer.from(message.serialize()),
            responseDeserialize: (bytes) => Default.deserialize(new Uint8Array(bytes))
        },
        SenderEvent: {
            path: "/srpc.SillyGirlService/SenderEvent",
            requestStream: false,
            responseStream: false,
            requestSerialize: (message) => Buffer.from(message.serialize()),
            requestDeserialize: (bytes) => SenderRequest.deserialize(new Uint8Array(bytes)),
            responseSerialize: (message) => Buffer.from(message.serialize()),
            responseDeserialize: (bytes) => Default.deserialize(new Uint8Array(bytes))
        },
        SenderReply: {
            path: "/srpc.SillyGirlService/SenderReply",
            requestStream: false,
            responseStream: false,
            requestSerialize: (message) => Buffer.from(message.serialize()),
            requestDeserialize: (bytes) => ReplyRequest.deserialize(new Uint8Array(bytes)),
            responseSerialize: (message) => Buffer.from(message.serialize()),
            responseDeserialize: (bytes) => Default.deserialize(new Uint8Array(bytes))
        },
        SenderAction: {
            path: "/srpc.SillyGirlService/SenderAction",
            requestStream: false,
            responseStream: false,
            requestSerialize: (message) => Buffer.from(message.serialize()),
            requestDeserialize: (bytes) => ReplyRequest.deserialize(new Uint8Array(bytes)),
            responseSerialize: (message) => Buffer.from(message.serialize()),
            responseDeserialize: (bytes) => Default.deserialize(new Uint8Array(bytes))
        },
        AdapterRegist: {
            path: "/srpc.SillyGirlService/AdapterRegist",
            requestStream: true,
            responseStream: true,
            requestSerialize: (message) => Buffer.from(message.serialize()),
            requestDeserialize: (bytes) => AdapterRegistRequest.deserialize(new Uint8Array(bytes)),
            responseSerialize: (message) => Buffer.from(message.serialize()),
            responseDeserialize: (bytes) => Default.deserialize(new Uint8Array(bytes))
        },
        AdapterReceive: {
            path: "/srpc.SillyGirlService/AdapterReceive",
            requestStream: false,
            responseStream: false,
            requestSerialize: (message) => Buffer.from(message.serialize()),
            requestDeserialize: (bytes) => AdapterRequest.deserialize(new Uint8Array(bytes)),
            responseSerialize: (message) => Buffer.from(message.serialize()),
            responseDeserialize: (bytes) => Default.deserialize(new Uint8Array(bytes))
        },
        AdapterPush: {
            path: "/srpc.SillyGirlService/AdapterPush",
            requestStream: false,
            responseStream: false,
            requestSerialize: (message) => Buffer.from(message.serialize()),
            requestDeserialize: (bytes) => AdapterRequest.deserialize(new Uint8Array(bytes)),
            responseSerialize: (message) => Buffer.from(message.serialize()),
            responseDeserialize: (bytes) => Default.deserialize(new Uint8Array(bytes))
        },
        AdapterDestroy: {
            path: "/srpc.SillyGirlService/AdapterDestroy",
            requestStream: false,
            responseStream: false,
            requestSerialize: (message) => Buffer.from(message.serialize()),
            requestDeserialize: (bytes) => AdapterRequest.deserialize(new Uint8Array(bytes)),
            responseSerialize: (message) => Buffer.from(message.serialize()),
            responseDeserialize: (bytes) => Empty.deserialize(new Uint8Array(bytes))
        },
        AdapterSender: {
            path: "/srpc.SillyGirlService/AdapterSender",
            requestStream: false,
            responseStream: false,
            requestSerialize: (message) => Buffer.from(message.serialize()),
            requestDeserialize: (bytes) => AdapterRequest.deserialize(new Uint8Array(bytes)),
            responseSerialize: (message) => Buffer.from(message.serialize()),
            responseDeserialize: (bytes) => Default.deserialize(new Uint8Array(bytes))
        }
    };
    srpc.UnimplementedSillyGirlServiceService = UnimplementedSillyGirlServiceService;
    class SillyGirlServiceClient extends grpc_1.makeGenericClientConstructor(UnimplementedSillyGirlServiceService.definition, "SillyGirlService", {}) {
        constructor(address, credentials, options) {
            super(address, credentials, options);
            this.BucketGet = (message, metadata, options, callback) => {
                return super.BucketGet(message, metadata, options, callback);
            };
            this.BucketSet = (message, metadata, options, callback) => {
                return super.BucketSet(message, metadata, options, callback);
            };
            this.BucketDelete = (message, metadata, options, callback) => {
                return super.BucketDelete(message, metadata, options, callback);
            };
            this.BucketKeys = (message, metadata, options, callback) => {
                return super.BucketKeys(message, metadata, options, callback);
            };
            this.BucketLen = (message, metadata, options, callback) => {
                return super.BucketLen(message, metadata, options, callback);
            };
            this.BucketGetAll = (message, metadata, options, callback) => {
                return super.BucketGetAll(message, metadata, options, callback);
            };
            this.BucketBuckets = (message, metadata, options, callback) => {
                return super.BucketBuckets(message, metadata, options, callback);
            };
            this.SenderGetUserId = (message, metadata, options, callback) => {
                return super.SenderGetUserId(message, metadata, options, callback);
            };
            this.SenderGetUserName = (message, metadata, options, callback) => {
                return super.SenderGetUserName(message, metadata, options, callback);
            };
            this.SenderGetChatId = (message, metadata, options, callback) => {
                return super.SenderGetChatId(message, metadata, options, callback);
            };
            this.SenderGetChatName = (message, metadata, options, callback) => {
                return super.SenderGetChatName(message, metadata, options, callback);
            };
            this.SenderGetMessageId = (message, metadata, options, callback) => {
                return super.SenderGetMessageId(message, metadata, options, callback);
            };
            this.SenderGetPlatform = (message, metadata, options, callback) => {
                return super.SenderGetPlatform(message, metadata, options, callback);
            };
            this.SenderGetBotId = (message, metadata, options, callback) => {
                return super.SenderGetBotId(message, metadata, options, callback);
            };
            this.SenderGetContent = (message, metadata, options, callback) => {
                return super.SenderGetContent(message, metadata, options, callback);
            };
            this.SenderSetContent = (message, metadata, options, callback) => {
                return super.SenderSetContent(message, metadata, options, callback);
            };
            this.SenderContinue = (message, metadata, options, callback) => {
                return super.SenderContinue(message, metadata, options, callback);
            };
            this.SenderListen = (message, metadata, options, callback) => {
                return super.SenderListen(message, metadata, options, callback);
            };
            this.SenderEvent = (message, metadata, options, callback) => {
                return super.SenderEvent(message, metadata, options, callback);
            };
            this.SenderReply = (message, metadata, options, callback) => {
                return super.SenderReply(message, metadata, options, callback);
            };
            this.SenderAction = (message, metadata, options, callback) => {
                return super.SenderAction(message, metadata, options, callback);
            };
            this.AdapterRegist = (metadata, options) => {
                return super.AdapterRegist(metadata, options);
            };
            this.AdapterReceive = (message, metadata, options, callback) => {
                return super.AdapterReceive(message, metadata, options, callback);
            };
            this.AdapterPush = (message, metadata, options, callback) => {
                return super.AdapterPush(message, metadata, options, callback);
            };
            this.AdapterDestroy = (message, metadata, options, callback) => {
                return super.AdapterDestroy(message, metadata, options, callback);
            };
            this.AdapterSender = (message, metadata, options, callback) => {
                return super.AdapterSender(message, metadata, options, callback);
            };
        }
    }
    srpc.SillyGirlServiceClient = SillyGirlServiceClient;
})(srpc || (exports.srpc = srpc = {}));
