/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.15.6
 * source: srpc.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
import * as grpc_1 from "@grpc/grpc-js";
export namespace srpc {
    export class Empty extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {}) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") { }
        }
        static fromObject(data: {}): Empty {
            const message = new Empty({});
            return message;
        }
        toObject() {
            const data: {} = {};
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Empty {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new Empty();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): Empty {
            return Empty.deserialize(bytes);
        }
    }
    export class Default extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            value?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("value" in data && data.value != undefined) {
                    this.value = data.value;
                }
            }
        }
        get value() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set value(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        static fromObject(data: {
            value?: string;
        }): Default {
            const message = new Default({});
            if (data.value != null) {
                message.value = data.value;
            }
            return message;
        }
        toObject() {
            const data: {
                value?: string;
            } = {};
            if (this.value != null) {
                data.value = this.value;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.value.length)
                writer.writeString(1, this.value);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Default {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new Default();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.value = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): Default {
            return Default.deserialize(bytes);
        }
    }
    export class BucketSetRequest extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            name?: string;
            key?: string;
            value?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("name" in data && data.name != undefined) {
                    this.name = data.name;
                }
                if ("key" in data && data.key != undefined) {
                    this.key = data.key;
                }
                if ("value" in data && data.value != undefined) {
                    this.value = data.value;
                }
            }
        }
        get name() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set name(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get key() {
            return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
        }
        set key(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        get value() {
            return pb_1.Message.getFieldWithDefault(this, 3, "") as string;
        }
        set value(value: string) {
            pb_1.Message.setField(this, 3, value);
        }
        static fromObject(data: {
            name?: string;
            key?: string;
            value?: string;
        }): BucketSetRequest {
            const message = new BucketSetRequest({});
            if (data.name != null) {
                message.name = data.name;
            }
            if (data.key != null) {
                message.key = data.key;
            }
            if (data.value != null) {
                message.value = data.value;
            }
            return message;
        }
        toObject() {
            const data: {
                name?: string;
                key?: string;
                value?: string;
            } = {};
            if (this.name != null) {
                data.name = this.name;
            }
            if (this.key != null) {
                data.key = this.key;
            }
            if (this.value != null) {
                data.value = this.value;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.name.length)
                writer.writeString(1, this.name);
            if (this.key.length)
                writer.writeString(2, this.key);
            if (this.value.length)
                writer.writeString(3, this.value);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): BucketSetRequest {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new BucketSetRequest();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.name = reader.readString();
                        break;
                    case 2:
                        message.key = reader.readString();
                        break;
                    case 3:
                        message.value = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): BucketSetRequest {
            return BucketSetRequest.deserialize(bytes);
        }
    }
    export class BucketSetResponse extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            changed?: boolean;
            message?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("changed" in data && data.changed != undefined) {
                    this.changed = data.changed;
                }
                if ("message" in data && data.message != undefined) {
                    this.message = data.message;
                }
            }
        }
        get changed() {
            return pb_1.Message.getFieldWithDefault(this, 1, false) as boolean;
        }
        set changed(value: boolean) {
            pb_1.Message.setField(this, 1, value);
        }
        get message() {
            return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
        }
        set message(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        static fromObject(data: {
            changed?: boolean;
            message?: string;
        }): BucketSetResponse {
            const message = new BucketSetResponse({});
            if (data.changed != null) {
                message.changed = data.changed;
            }
            if (data.message != null) {
                message.message = data.message;
            }
            return message;
        }
        toObject() {
            const data: {
                changed?: boolean;
                message?: string;
            } = {};
            if (this.changed != null) {
                data.changed = this.changed;
            }
            if (this.message != null) {
                data.message = this.message;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.changed != false)
                writer.writeBool(1, this.changed);
            if (this.message.length)
                writer.writeString(2, this.message);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): BucketSetResponse {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new BucketSetResponse();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.changed = reader.readBool();
                        break;
                    case 2:
                        message.message = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): BucketSetResponse {
            return BucketSetResponse.deserialize(bytes);
        }
    }
    export class BucketKeyRequest extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            name?: string;
            key?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("name" in data && data.name != undefined) {
                    this.name = data.name;
                }
                if ("key" in data && data.key != undefined) {
                    this.key = data.key;
                }
            }
        }
        get name() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set name(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get key() {
            return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
        }
        set key(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        static fromObject(data: {
            name?: string;
            key?: string;
        }): BucketKeyRequest {
            const message = new BucketKeyRequest({});
            if (data.name != null) {
                message.name = data.name;
            }
            if (data.key != null) {
                message.key = data.key;
            }
            return message;
        }
        toObject() {
            const data: {
                name?: string;
                key?: string;
            } = {};
            if (this.name != null) {
                data.name = this.name;
            }
            if (this.key != null) {
                data.key = this.key;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.name.length)
                writer.writeString(1, this.name);
            if (this.key.length)
                writer.writeString(2, this.key);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): BucketKeyRequest {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new BucketKeyRequest();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.name = reader.readString();
                        break;
                    case 2:
                        message.key = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): BucketKeyRequest {
            return BucketKeyRequest.deserialize(bytes);
        }
    }
    export class BucketRequest extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            name?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("name" in data && data.name != undefined) {
                    this.name = data.name;
                }
            }
        }
        get name() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set name(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        static fromObject(data: {
            name?: string;
        }): BucketRequest {
            const message = new BucketRequest({});
            if (data.name != null) {
                message.name = data.name;
            }
            return message;
        }
        toObject() {
            const data: {
                name?: string;
            } = {};
            if (this.name != null) {
                data.name = this.name;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.name.length)
                writer.writeString(1, this.name);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): BucketRequest {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new BucketRequest();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.name = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): BucketRequest {
            return BucketRequest.deserialize(bytes);
        }
    }
    export class BucketKeysResponse extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            keys?: string[];
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [1], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("keys" in data && data.keys != undefined) {
                    this.keys = data.keys;
                }
            }
        }
        get keys() {
            return pb_1.Message.getFieldWithDefault(this, 1, []) as string[];
        }
        set keys(value: string[]) {
            pb_1.Message.setField(this, 1, value);
        }
        static fromObject(data: {
            keys?: string[];
        }): BucketKeysResponse {
            const message = new BucketKeysResponse({});
            if (data.keys != null) {
                message.keys = data.keys;
            }
            return message;
        }
        toObject() {
            const data: {
                keys?: string[];
            } = {};
            if (this.keys != null) {
                data.keys = this.keys;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.keys.length)
                writer.writeRepeatedString(1, this.keys);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): BucketKeysResponse {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new BucketKeysResponse();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        pb_1.Message.addToRepeatedField(message, 1, reader.readString());
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): BucketKeysResponse {
            return BucketKeysResponse.deserialize(bytes);
        }
    }
    export class LenResponse extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            length?: number;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("length" in data && data.length != undefined) {
                    this.length = data.length;
                }
            }
        }
        get length() {
            return pb_1.Message.getFieldWithDefault(this, 1, 0) as number;
        }
        set length(value: number) {
            pb_1.Message.setField(this, 1, value);
        }
        static fromObject(data: {
            length?: number;
        }): LenResponse {
            const message = new LenResponse({});
            if (data.length != null) {
                message.length = data.length;
            }
            return message;
        }
        toObject() {
            const data: {
                length?: number;
            } = {};
            if (this.length != null) {
                data.length = this.length;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.length != 0)
                writer.writeInt32(1, this.length);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): LenResponse {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new LenResponse();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.length = reader.readInt32();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): LenResponse {
            return LenResponse.deserialize(bytes);
        }
    }
    export class BucketsResponse extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            buckets?: string[];
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [1], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("buckets" in data && data.buckets != undefined) {
                    this.buckets = data.buckets;
                }
            }
        }
        get buckets() {
            return pb_1.Message.getFieldWithDefault(this, 1, []) as string[];
        }
        set buckets(value: string[]) {
            pb_1.Message.setField(this, 1, value);
        }
        static fromObject(data: {
            buckets?: string[];
        }): BucketsResponse {
            const message = new BucketsResponse({});
            if (data.buckets != null) {
                message.buckets = data.buckets;
            }
            return message;
        }
        toObject() {
            const data: {
                buckets?: string[];
            } = {};
            if (this.buckets != null) {
                data.buckets = this.buckets;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.buckets.length)
                writer.writeRepeatedString(1, this.buckets);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): BucketsResponse {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new BucketsResponse();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        pb_1.Message.addToRepeatedField(message, 1, reader.readString());
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): BucketsResponse {
            return BucketsResponse.deserialize(bytes);
        }
    }
    export class SenderRequest extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            uuid?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("uuid" in data && data.uuid != undefined) {
                    this.uuid = data.uuid;
                }
            }
        }
        get uuid() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set uuid(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        static fromObject(data: {
            uuid?: string;
        }): SenderRequest {
            const message = new SenderRequest({});
            if (data.uuid != null) {
                message.uuid = data.uuid;
            }
            return message;
        }
        toObject() {
            const data: {
                uuid?: string;
            } = {};
            if (this.uuid != null) {
                data.uuid = this.uuid;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.uuid.length)
                writer.writeString(1, this.uuid);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): SenderRequest {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new SenderRequest();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.uuid = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): SenderRequest {
            return SenderRequest.deserialize(bytes);
        }
    }
    export class ReplyRequest extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            uuid?: string;
            content?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("uuid" in data && data.uuid != undefined) {
                    this.uuid = data.uuid;
                }
                if ("content" in data && data.content != undefined) {
                    this.content = data.content;
                }
            }
        }
        get uuid() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set uuid(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get content() {
            return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
        }
        set content(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        static fromObject(data: {
            uuid?: string;
            content?: string;
        }): ReplyRequest {
            const message = new ReplyRequest({});
            if (data.uuid != null) {
                message.uuid = data.uuid;
            }
            if (data.content != null) {
                message.content = data.content;
            }
            return message;
        }
        toObject() {
            const data: {
                uuid?: string;
                content?: string;
            } = {};
            if (this.uuid != null) {
                data.uuid = this.uuid;
            }
            if (this.content != null) {
                data.content = this.content;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.uuid.length)
                writer.writeString(1, this.uuid);
            if (this.content.length)
                writer.writeString(2, this.content);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): ReplyRequest {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new ReplyRequest();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.uuid = reader.readString();
                        break;
                    case 2:
                        message.content = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): ReplyRequest {
            return ReplyRequest.deserialize(bytes);
        }
    }
    export class SenderContentRequest extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            uuid?: string;
            content?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("uuid" in data && data.uuid != undefined) {
                    this.uuid = data.uuid;
                }
                if ("content" in data && data.content != undefined) {
                    this.content = data.content;
                }
            }
        }
        get uuid() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set uuid(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get content() {
            return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
        }
        set content(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        static fromObject(data: {
            uuid?: string;
            content?: string;
        }): SenderContentRequest {
            const message = new SenderContentRequest({});
            if (data.uuid != null) {
                message.uuid = data.uuid;
            }
            if (data.content != null) {
                message.content = data.content;
            }
            return message;
        }
        toObject() {
            const data: {
                uuid?: string;
                content?: string;
            } = {};
            if (this.uuid != null) {
                data.uuid = this.uuid;
            }
            if (this.content != null) {
                data.content = this.content;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.uuid.length)
                writer.writeString(1, this.uuid);
            if (this.content.length)
                writer.writeString(2, this.content);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): SenderContentRequest {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new SenderContentRequest();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.uuid = reader.readString();
                        break;
                    case 2:
                        message.content = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): SenderContentRequest {
            return SenderContentRequest.deserialize(bytes);
        }
    }
    export class SenderListenRequest extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            uuid?: string;
            rules?: string[];
            timeout?: number;
            listen_group?: boolean;
            listen_private?: boolean;
            require_admin?: boolean;
            allow_platforms?: string[];
            prohibit_platforms?: string[];
            allow_users?: string[];
            prohibit_users?: string[];
            allow_groups?: string[];
            prohibit_groups?: string[];
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [2, 7, 8, 9, 10, 11, 12], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("uuid" in data && data.uuid != undefined) {
                    this.uuid = data.uuid;
                }
                if ("rules" in data && data.rules != undefined) {
                    this.rules = data.rules;
                }
                if ("timeout" in data && data.timeout != undefined) {
                    this.timeout = data.timeout;
                }
                if ("listen_group" in data && data.listen_group != undefined) {
                    this.listen_group = data.listen_group;
                }
                if ("listen_private" in data && data.listen_private != undefined) {
                    this.listen_private = data.listen_private;
                }
                if ("require_admin" in data && data.require_admin != undefined) {
                    this.require_admin = data.require_admin;
                }
                if ("allow_platforms" in data && data.allow_platforms != undefined) {
                    this.allow_platforms = data.allow_platforms;
                }
                if ("prohibit_platforms" in data && data.prohibit_platforms != undefined) {
                    this.prohibit_platforms = data.prohibit_platforms;
                }
                if ("allow_users" in data && data.allow_users != undefined) {
                    this.allow_users = data.allow_users;
                }
                if ("prohibit_users" in data && data.prohibit_users != undefined) {
                    this.prohibit_users = data.prohibit_users;
                }
                if ("allow_groups" in data && data.allow_groups != undefined) {
                    this.allow_groups = data.allow_groups;
                }
                if ("prohibit_groups" in data && data.prohibit_groups != undefined) {
                    this.prohibit_groups = data.prohibit_groups;
                }
            }
        }
        get uuid() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set uuid(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get rules() {
            return pb_1.Message.getFieldWithDefault(this, 2, []) as string[];
        }
        set rules(value: string[]) {
            pb_1.Message.setField(this, 2, value);
        }
        get timeout() {
            return pb_1.Message.getFieldWithDefault(this, 3, 0) as number;
        }
        set timeout(value: number) {
            pb_1.Message.setField(this, 3, value);
        }
        get listen_group() {
            return pb_1.Message.getFieldWithDefault(this, 4, false) as boolean;
        }
        set listen_group(value: boolean) {
            pb_1.Message.setField(this, 4, value);
        }
        get listen_private() {
            return pb_1.Message.getFieldWithDefault(this, 5, false) as boolean;
        }
        set listen_private(value: boolean) {
            pb_1.Message.setField(this, 5, value);
        }
        get require_admin() {
            return pb_1.Message.getFieldWithDefault(this, 6, false) as boolean;
        }
        set require_admin(value: boolean) {
            pb_1.Message.setField(this, 6, value);
        }
        get allow_platforms() {
            return pb_1.Message.getFieldWithDefault(this, 7, []) as string[];
        }
        set allow_platforms(value: string[]) {
            pb_1.Message.setField(this, 7, value);
        }
        get prohibit_platforms() {
            return pb_1.Message.getFieldWithDefault(this, 8, []) as string[];
        }
        set prohibit_platforms(value: string[]) {
            pb_1.Message.setField(this, 8, value);
        }
        get allow_users() {
            return pb_1.Message.getFieldWithDefault(this, 9, []) as string[];
        }
        set allow_users(value: string[]) {
            pb_1.Message.setField(this, 9, value);
        }
        get prohibit_users() {
            return pb_1.Message.getFieldWithDefault(this, 10, []) as string[];
        }
        set prohibit_users(value: string[]) {
            pb_1.Message.setField(this, 10, value);
        }
        get allow_groups() {
            return pb_1.Message.getFieldWithDefault(this, 11, []) as string[];
        }
        set allow_groups(value: string[]) {
            pb_1.Message.setField(this, 11, value);
        }
        get prohibit_groups() {
            return pb_1.Message.getFieldWithDefault(this, 12, []) as string[];
        }
        set prohibit_groups(value: string[]) {
            pb_1.Message.setField(this, 12, value);
        }
        static fromObject(data: {
            uuid?: string;
            rules?: string[];
            timeout?: number;
            listen_group?: boolean;
            listen_private?: boolean;
            require_admin?: boolean;
            allow_platforms?: string[];
            prohibit_platforms?: string[];
            allow_users?: string[];
            prohibit_users?: string[];
            allow_groups?: string[];
            prohibit_groups?: string[];
        }): SenderListenRequest {
            const message = new SenderListenRequest({});
            if (data.uuid != null) {
                message.uuid = data.uuid;
            }
            if (data.rules != null) {
                message.rules = data.rules;
            }
            if (data.timeout != null) {
                message.timeout = data.timeout;
            }
            if (data.listen_group != null) {
                message.listen_group = data.listen_group;
            }
            if (data.listen_private != null) {
                message.listen_private = data.listen_private;
            }
            if (data.require_admin != null) {
                message.require_admin = data.require_admin;
            }
            if (data.allow_platforms != null) {
                message.allow_platforms = data.allow_platforms;
            }
            if (data.prohibit_platforms != null) {
                message.prohibit_platforms = data.prohibit_platforms;
            }
            if (data.allow_users != null) {
                message.allow_users = data.allow_users;
            }
            if (data.prohibit_users != null) {
                message.prohibit_users = data.prohibit_users;
            }
            if (data.allow_groups != null) {
                message.allow_groups = data.allow_groups;
            }
            if (data.prohibit_groups != null) {
                message.prohibit_groups = data.prohibit_groups;
            }
            return message;
        }
        toObject() {
            const data: {
                uuid?: string;
                rules?: string[];
                timeout?: number;
                listen_group?: boolean;
                listen_private?: boolean;
                require_admin?: boolean;
                allow_platforms?: string[];
                prohibit_platforms?: string[];
                allow_users?: string[];
                prohibit_users?: string[];
                allow_groups?: string[];
                prohibit_groups?: string[];
            } = {};
            if (this.uuid != null) {
                data.uuid = this.uuid;
            }
            if (this.rules != null) {
                data.rules = this.rules;
            }
            if (this.timeout != null) {
                data.timeout = this.timeout;
            }
            if (this.listen_group != null) {
                data.listen_group = this.listen_group;
            }
            if (this.listen_private != null) {
                data.listen_private = this.listen_private;
            }
            if (this.require_admin != null) {
                data.require_admin = this.require_admin;
            }
            if (this.allow_platforms != null) {
                data.allow_platforms = this.allow_platforms;
            }
            if (this.prohibit_platforms != null) {
                data.prohibit_platforms = this.prohibit_platforms;
            }
            if (this.allow_users != null) {
                data.allow_users = this.allow_users;
            }
            if (this.prohibit_users != null) {
                data.prohibit_users = this.prohibit_users;
            }
            if (this.allow_groups != null) {
                data.allow_groups = this.allow_groups;
            }
            if (this.prohibit_groups != null) {
                data.prohibit_groups = this.prohibit_groups;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.uuid.length)
                writer.writeString(1, this.uuid);
            if (this.rules.length)
                writer.writeRepeatedString(2, this.rules);
            if (this.timeout != 0)
                writer.writeInt32(3, this.timeout);
            if (this.listen_group != false)
                writer.writeBool(4, this.listen_group);
            if (this.listen_private != false)
                writer.writeBool(5, this.listen_private);
            if (this.require_admin != false)
                writer.writeBool(6, this.require_admin);
            if (this.allow_platforms.length)
                writer.writeRepeatedString(7, this.allow_platforms);
            if (this.prohibit_platforms.length)
                writer.writeRepeatedString(8, this.prohibit_platforms);
            if (this.allow_users.length)
                writer.writeRepeatedString(9, this.allow_users);
            if (this.prohibit_users.length)
                writer.writeRepeatedString(10, this.prohibit_users);
            if (this.allow_groups.length)
                writer.writeRepeatedString(11, this.allow_groups);
            if (this.prohibit_groups.length)
                writer.writeRepeatedString(12, this.prohibit_groups);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): SenderListenRequest {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new SenderListenRequest();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.uuid = reader.readString();
                        break;
                    case 2:
                        pb_1.Message.addToRepeatedField(message, 2, reader.readString());
                        break;
                    case 3:
                        message.timeout = reader.readInt32();
                        break;
                    case 4:
                        message.listen_group = reader.readBool();
                        break;
                    case 5:
                        message.listen_private = reader.readBool();
                        break;
                    case 6:
                        message.require_admin = reader.readBool();
                        break;
                    case 7:
                        pb_1.Message.addToRepeatedField(message, 7, reader.readString());
                        break;
                    case 8:
                        pb_1.Message.addToRepeatedField(message, 8, reader.readString());
                        break;
                    case 9:
                        pb_1.Message.addToRepeatedField(message, 9, reader.readString());
                        break;
                    case 10:
                        pb_1.Message.addToRepeatedField(message, 10, reader.readString());
                        break;
                    case 11:
                        pb_1.Message.addToRepeatedField(message, 11, reader.readString());
                        break;
                    case 12:
                        pb_1.Message.addToRepeatedField(message, 12, reader.readString());
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): SenderListenRequest {
            return SenderListenRequest.deserialize(bytes);
        }
    }
    export class AdapterRegistRequest extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            platform?: string;
            bot_id?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("platform" in data && data.platform != undefined) {
                    this.platform = data.platform;
                }
                if ("bot_id" in data && data.bot_id != undefined) {
                    this.bot_id = data.bot_id;
                }
            }
        }
        get platform() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set platform(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get bot_id() {
            return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
        }
        set bot_id(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        static fromObject(data: {
            platform?: string;
            bot_id?: string;
        }): AdapterRegistRequest {
            const message = new AdapterRegistRequest({});
            if (data.platform != null) {
                message.platform = data.platform;
            }
            if (data.bot_id != null) {
                message.bot_id = data.bot_id;
            }
            return message;
        }
        toObject() {
            const data: {
                platform?: string;
                bot_id?: string;
            } = {};
            if (this.platform != null) {
                data.platform = this.platform;
            }
            if (this.bot_id != null) {
                data.bot_id = this.bot_id;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.platform.length)
                writer.writeString(1, this.platform);
            if (this.bot_id.length)
                writer.writeString(2, this.bot_id);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): AdapterRegistRequest {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new AdapterRegistRequest();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.platform = reader.readString();
                        break;
                    case 2:
                        message.bot_id = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): AdapterRegistRequest {
            return AdapterRegistRequest.deserialize(bytes);
        }
    }
    export class AdapterRequest extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            platform?: string;
            bot_id?: string;
            value?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("platform" in data && data.platform != undefined) {
                    this.platform = data.platform;
                }
                if ("bot_id" in data && data.bot_id != undefined) {
                    this.bot_id = data.bot_id;
                }
                if ("value" in data && data.value != undefined) {
                    this.value = data.value;
                }
            }
        }
        get platform() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set platform(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get bot_id() {
            return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
        }
        set bot_id(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        get value() {
            return pb_1.Message.getFieldWithDefault(this, 3, "") as string;
        }
        set value(value: string) {
            pb_1.Message.setField(this, 3, value);
        }
        static fromObject(data: {
            platform?: string;
            bot_id?: string;
            value?: string;
        }): AdapterRequest {
            const message = new AdapterRequest({});
            if (data.platform != null) {
                message.platform = data.platform;
            }
            if (data.bot_id != null) {
                message.bot_id = data.bot_id;
            }
            if (data.value != null) {
                message.value = data.value;
            }
            return message;
        }
        toObject() {
            const data: {
                platform?: string;
                bot_id?: string;
                value?: string;
            } = {};
            if (this.platform != null) {
                data.platform = this.platform;
            }
            if (this.bot_id != null) {
                data.bot_id = this.bot_id;
            }
            if (this.value != null) {
                data.value = this.value;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.platform.length)
                writer.writeString(1, this.platform);
            if (this.bot_id.length)
                writer.writeString(2, this.bot_id);
            if (this.value.length)
                writer.writeString(3, this.value);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): AdapterRequest {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new AdapterRequest();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.platform = reader.readString();
                        break;
                    case 2:
                        message.bot_id = reader.readString();
                        break;
                    case 3:
                        message.value = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): AdapterRequest {
            return AdapterRequest.deserialize(bytes);
        }
    }
    interface GrpcUnaryServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, metadata: grpc_1.Metadata, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
    }
    interface GrpcStreamServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): grpc_1.ClientReadableStream<R>;
        (message: P, options?: grpc_1.CallOptions): grpc_1.ClientReadableStream<R>;
    }
    interface GrpWritableServiceInterface<P, R> {
        (metadata: grpc_1.Metadata, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (metadata: grpc_1.Metadata, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
    }
    interface GrpcChunkServiceInterface<P, R> {
        (metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): grpc_1.ClientDuplexStream<P, R>;
        (options?: grpc_1.CallOptions): grpc_1.ClientDuplexStream<P, R>;
    }
    interface GrpcPromiseServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): Promise<R>;
        (message: P, options?: grpc_1.CallOptions): Promise<R>;
    }
    export abstract class UnimplementedSillyGirlServiceService {
        static definition = {
            BucketGet: {
                path: "/srpc.SillyGirlService/BucketGet",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: BucketKeyRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => BucketKeyRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: Default) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => Default.deserialize(new Uint8Array(bytes))
            },
            BucketSet: {
                path: "/srpc.SillyGirlService/BucketSet",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: BucketSetRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => BucketSetRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: BucketSetResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => BucketSetResponse.deserialize(new Uint8Array(bytes))
            },
            BucketDelete: {
                path: "/srpc.SillyGirlService/BucketDelete",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: BucketRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => BucketRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: Empty) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => Empty.deserialize(new Uint8Array(bytes))
            },
            BucketKeys: {
                path: "/srpc.SillyGirlService/BucketKeys",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: BucketRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => BucketRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: BucketKeysResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => BucketKeysResponse.deserialize(new Uint8Array(bytes))
            },
            BucketLen: {
                path: "/srpc.SillyGirlService/BucketLen",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: BucketRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => BucketRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: LenResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => LenResponse.deserialize(new Uint8Array(bytes))
            },
            BucketGetAll: {
                path: "/srpc.SillyGirlService/BucketGetAll",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: BucketRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => BucketRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: Default) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => Default.deserialize(new Uint8Array(bytes))
            },
            BucketBuckets: {
                path: "/srpc.SillyGirlService/BucketBuckets",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: Empty) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => Empty.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: BucketsResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => BucketsResponse.deserialize(new Uint8Array(bytes))
            },
            SenderGetUserId: {
                path: "/srpc.SillyGirlService/SenderGetUserId",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: SenderRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => SenderRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: Default) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => Default.deserialize(new Uint8Array(bytes))
            },
            SenderGetUserName: {
                path: "/srpc.SillyGirlService/SenderGetUserName",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: SenderRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => SenderRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: Default) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => Default.deserialize(new Uint8Array(bytes))
            },
            SenderGetChatId: {
                path: "/srpc.SillyGirlService/SenderGetChatId",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: SenderRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => SenderRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: Default) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => Default.deserialize(new Uint8Array(bytes))
            },
            SenderGetChatName: {
                path: "/srpc.SillyGirlService/SenderGetChatName",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: SenderRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => SenderRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: Default) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => Default.deserialize(new Uint8Array(bytes))
            },
            SenderGetMessageId: {
                path: "/srpc.SillyGirlService/SenderGetMessageId",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: SenderRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => SenderRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: Default) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => Default.deserialize(new Uint8Array(bytes))
            },
            SenderGetPlatform: {
                path: "/srpc.SillyGirlService/SenderGetPlatform",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: SenderRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => SenderRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: Default) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => Default.deserialize(new Uint8Array(bytes))
            },
            SenderGetBotId: {
                path: "/srpc.SillyGirlService/SenderGetBotId",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: SenderRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => SenderRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: Default) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => Default.deserialize(new Uint8Array(bytes))
            },
            SenderGetContent: {
                path: "/srpc.SillyGirlService/SenderGetContent",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: SenderRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => SenderRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: Default) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => Default.deserialize(new Uint8Array(bytes))
            },
            SenderSetContent: {
                path: "/srpc.SillyGirlService/SenderSetContent",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: SenderContentRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => SenderContentRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: Empty) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => Empty.deserialize(new Uint8Array(bytes))
            },
            SenderContinue: {
                path: "/srpc.SillyGirlService/SenderContinue",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: SenderRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => SenderRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: Empty) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => Empty.deserialize(new Uint8Array(bytes))
            },
            SenderListen: {
                path: "/srpc.SillyGirlService/SenderListen",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: SenderListenRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => SenderListenRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: Default) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => Default.deserialize(new Uint8Array(bytes))
            },
            SenderEvent: {
                path: "/srpc.SillyGirlService/SenderEvent",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: SenderRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => SenderRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: Default) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => Default.deserialize(new Uint8Array(bytes))
            },
            SenderReply: {
                path: "/srpc.SillyGirlService/SenderReply",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: ReplyRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => ReplyRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: Default) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => Default.deserialize(new Uint8Array(bytes))
            },
            SenderAction: {
                path: "/srpc.SillyGirlService/SenderAction",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: ReplyRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => ReplyRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: Default) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => Default.deserialize(new Uint8Array(bytes))
            },
            AdapterRegist: {
                path: "/srpc.SillyGirlService/AdapterRegist",
                requestStream: true,
                responseStream: true,
                requestSerialize: (message: AdapterRegistRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => AdapterRegistRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: Default) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => Default.deserialize(new Uint8Array(bytes))
            },
            AdapterReceive: {
                path: "/srpc.SillyGirlService/AdapterReceive",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: AdapterRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => AdapterRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: Default) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => Default.deserialize(new Uint8Array(bytes))
            },
            AdapterPush: {
                path: "/srpc.SillyGirlService/AdapterPush",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: AdapterRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => AdapterRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: Default) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => Default.deserialize(new Uint8Array(bytes))
            },
            AdapterDestroy: {
                path: "/srpc.SillyGirlService/AdapterDestroy",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: AdapterRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => AdapterRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: Empty) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => Empty.deserialize(new Uint8Array(bytes))
            },
            AdapterSender: {
                path: "/srpc.SillyGirlService/AdapterSender",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: AdapterRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => AdapterRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: Default) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => Default.deserialize(new Uint8Array(bytes))
            }
        };
        [method: string]: grpc_1.UntypedHandleCall;
        abstract BucketGet(call: grpc_1.ServerUnaryCall<BucketKeyRequest, Default>, callback: grpc_1.sendUnaryData<Default>): void;
        abstract BucketSet(call: grpc_1.ServerUnaryCall<BucketSetRequest, BucketSetResponse>, callback: grpc_1.sendUnaryData<BucketSetResponse>): void;
        abstract BucketDelete(call: grpc_1.ServerUnaryCall<BucketRequest, Empty>, callback: grpc_1.sendUnaryData<Empty>): void;
        abstract BucketKeys(call: grpc_1.ServerUnaryCall<BucketRequest, BucketKeysResponse>, callback: grpc_1.sendUnaryData<BucketKeysResponse>): void;
        abstract BucketLen(call: grpc_1.ServerUnaryCall<BucketRequest, LenResponse>, callback: grpc_1.sendUnaryData<LenResponse>): void;
        abstract BucketGetAll(call: grpc_1.ServerUnaryCall<BucketRequest, Default>, callback: grpc_1.sendUnaryData<Default>): void;
        abstract BucketBuckets(call: grpc_1.ServerUnaryCall<Empty, BucketsResponse>, callback: grpc_1.sendUnaryData<BucketsResponse>): void;
        abstract SenderGetUserId(call: grpc_1.ServerUnaryCall<SenderRequest, Default>, callback: grpc_1.sendUnaryData<Default>): void;
        abstract SenderGetUserName(call: grpc_1.ServerUnaryCall<SenderRequest, Default>, callback: grpc_1.sendUnaryData<Default>): void;
        abstract SenderGetChatId(call: grpc_1.ServerUnaryCall<SenderRequest, Default>, callback: grpc_1.sendUnaryData<Default>): void;
        abstract SenderGetChatName(call: grpc_1.ServerUnaryCall<SenderRequest, Default>, callback: grpc_1.sendUnaryData<Default>): void;
        abstract SenderGetMessageId(call: grpc_1.ServerUnaryCall<SenderRequest, Default>, callback: grpc_1.sendUnaryData<Default>): void;
        abstract SenderGetPlatform(call: grpc_1.ServerUnaryCall<SenderRequest, Default>, callback: grpc_1.sendUnaryData<Default>): void;
        abstract SenderGetBotId(call: grpc_1.ServerUnaryCall<SenderRequest, Default>, callback: grpc_1.sendUnaryData<Default>): void;
        abstract SenderGetContent(call: grpc_1.ServerUnaryCall<SenderRequest, Default>, callback: grpc_1.sendUnaryData<Default>): void;
        abstract SenderSetContent(call: grpc_1.ServerUnaryCall<SenderContentRequest, Empty>, callback: grpc_1.sendUnaryData<Empty>): void;
        abstract SenderContinue(call: grpc_1.ServerUnaryCall<SenderRequest, Empty>, callback: grpc_1.sendUnaryData<Empty>): void;
        abstract SenderListen(call: grpc_1.ServerUnaryCall<SenderListenRequest, Default>, callback: grpc_1.sendUnaryData<Default>): void;
        abstract SenderEvent(call: grpc_1.ServerUnaryCall<SenderRequest, Default>, callback: grpc_1.sendUnaryData<Default>): void;
        abstract SenderReply(call: grpc_1.ServerUnaryCall<ReplyRequest, Default>, callback: grpc_1.sendUnaryData<Default>): void;
        abstract SenderAction(call: grpc_1.ServerUnaryCall<ReplyRequest, Default>, callback: grpc_1.sendUnaryData<Default>): void;
        abstract AdapterRegist(call: grpc_1.ServerDuplexStream<AdapterRegistRequest, Default>): void;
        abstract AdapterReceive(call: grpc_1.ServerUnaryCall<AdapterRequest, Default>, callback: grpc_1.sendUnaryData<Default>): void;
        abstract AdapterPush(call: grpc_1.ServerUnaryCall<AdapterRequest, Default>, callback: grpc_1.sendUnaryData<Default>): void;
        abstract AdapterDestroy(call: grpc_1.ServerUnaryCall<AdapterRequest, Empty>, callback: grpc_1.sendUnaryData<Empty>): void;
        abstract AdapterSender(call: grpc_1.ServerUnaryCall<AdapterRequest, Default>, callback: grpc_1.sendUnaryData<Default>): void;
    }
    export class SillyGirlServiceClient extends grpc_1.makeGenericClientConstructor(UnimplementedSillyGirlServiceService.definition, "SillyGirlService", {}) {
        constructor(address: string, credentials: grpc_1.ChannelCredentials, options?: Partial<grpc_1.ChannelOptions>) {
            super(address, credentials, options);
        }
        BucketGet: GrpcUnaryServiceInterface<BucketKeyRequest, Default> = (message: BucketKeyRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<Default>, options?: grpc_1.CallOptions | grpc_1.requestCallback<Default>, callback?: grpc_1.requestCallback<Default>): grpc_1.ClientUnaryCall => {
            return super.BucketGet(message, metadata, options, callback);
        };
        BucketSet: GrpcUnaryServiceInterface<BucketSetRequest, BucketSetResponse> = (message: BucketSetRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<BucketSetResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<BucketSetResponse>, callback?: grpc_1.requestCallback<BucketSetResponse>): grpc_1.ClientUnaryCall => {
            return super.BucketSet(message, metadata, options, callback);
        };
        BucketDelete: GrpcUnaryServiceInterface<BucketRequest, Empty> = (message: BucketRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<Empty>, options?: grpc_1.CallOptions | grpc_1.requestCallback<Empty>, callback?: grpc_1.requestCallback<Empty>): grpc_1.ClientUnaryCall => {
            return super.BucketDelete(message, metadata, options, callback);
        };
        BucketKeys: GrpcUnaryServiceInterface<BucketRequest, BucketKeysResponse> = (message: BucketRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<BucketKeysResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<BucketKeysResponse>, callback?: grpc_1.requestCallback<BucketKeysResponse>): grpc_1.ClientUnaryCall => {
            return super.BucketKeys(message, metadata, options, callback);
        };
        BucketLen: GrpcUnaryServiceInterface<BucketRequest, LenResponse> = (message: BucketRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<LenResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<LenResponse>, callback?: grpc_1.requestCallback<LenResponse>): grpc_1.ClientUnaryCall => {
            return super.BucketLen(message, metadata, options, callback);
        };
        BucketGetAll: GrpcUnaryServiceInterface<BucketRequest, Default> = (message: BucketRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<Default>, options?: grpc_1.CallOptions | grpc_1.requestCallback<Default>, callback?: grpc_1.requestCallback<Default>): grpc_1.ClientUnaryCall => {
            return super.BucketGetAll(message, metadata, options, callback);
        };
        BucketBuckets: GrpcUnaryServiceInterface<Empty, BucketsResponse> = (message: Empty, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<BucketsResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<BucketsResponse>, callback?: grpc_1.requestCallback<BucketsResponse>): grpc_1.ClientUnaryCall => {
            return super.BucketBuckets(message, metadata, options, callback);
        };
        SenderGetUserId: GrpcUnaryServiceInterface<SenderRequest, Default> = (message: SenderRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<Default>, options?: grpc_1.CallOptions | grpc_1.requestCallback<Default>, callback?: grpc_1.requestCallback<Default>): grpc_1.ClientUnaryCall => {
            return super.SenderGetUserId(message, metadata, options, callback);
        };
        SenderGetUserName: GrpcUnaryServiceInterface<SenderRequest, Default> = (message: SenderRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<Default>, options?: grpc_1.CallOptions | grpc_1.requestCallback<Default>, callback?: grpc_1.requestCallback<Default>): grpc_1.ClientUnaryCall => {
            return super.SenderGetUserName(message, metadata, options, callback);
        };
        SenderGetChatId: GrpcUnaryServiceInterface<SenderRequest, Default> = (message: SenderRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<Default>, options?: grpc_1.CallOptions | grpc_1.requestCallback<Default>, callback?: grpc_1.requestCallback<Default>): grpc_1.ClientUnaryCall => {
            return super.SenderGetChatId(message, metadata, options, callback);
        };
        SenderGetChatName: GrpcUnaryServiceInterface<SenderRequest, Default> = (message: SenderRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<Default>, options?: grpc_1.CallOptions | grpc_1.requestCallback<Default>, callback?: grpc_1.requestCallback<Default>): grpc_1.ClientUnaryCall => {
            return super.SenderGetChatName(message, metadata, options, callback);
        };
        SenderGetMessageId: GrpcUnaryServiceInterface<SenderRequest, Default> = (message: SenderRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<Default>, options?: grpc_1.CallOptions | grpc_1.requestCallback<Default>, callback?: grpc_1.requestCallback<Default>): grpc_1.ClientUnaryCall => {
            return super.SenderGetMessageId(message, metadata, options, callback);
        };
        SenderGetPlatform: GrpcUnaryServiceInterface<SenderRequest, Default> = (message: SenderRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<Default>, options?: grpc_1.CallOptions | grpc_1.requestCallback<Default>, callback?: grpc_1.requestCallback<Default>): grpc_1.ClientUnaryCall => {
            return super.SenderGetPlatform(message, metadata, options, callback);
        };
        SenderGetBotId: GrpcUnaryServiceInterface<SenderRequest, Default> = (message: SenderRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<Default>, options?: grpc_1.CallOptions | grpc_1.requestCallback<Default>, callback?: grpc_1.requestCallback<Default>): grpc_1.ClientUnaryCall => {
            return super.SenderGetBotId(message, metadata, options, callback);
        };
        SenderGetContent: GrpcUnaryServiceInterface<SenderRequest, Default> = (message: SenderRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<Default>, options?: grpc_1.CallOptions | grpc_1.requestCallback<Default>, callback?: grpc_1.requestCallback<Default>): grpc_1.ClientUnaryCall => {
            return super.SenderGetContent(message, metadata, options, callback);
        };
        SenderSetContent: GrpcUnaryServiceInterface<SenderContentRequest, Empty> = (message: SenderContentRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<Empty>, options?: grpc_1.CallOptions | grpc_1.requestCallback<Empty>, callback?: grpc_1.requestCallback<Empty>): grpc_1.ClientUnaryCall => {
            return super.SenderSetContent(message, metadata, options, callback);
        };
        SenderContinue: GrpcUnaryServiceInterface<SenderRequest, Empty> = (message: SenderRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<Empty>, options?: grpc_1.CallOptions | grpc_1.requestCallback<Empty>, callback?: grpc_1.requestCallback<Empty>): grpc_1.ClientUnaryCall => {
            return super.SenderContinue(message, metadata, options, callback);
        };
        SenderListen: GrpcUnaryServiceInterface<SenderListenRequest, Default> = (message: SenderListenRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<Default>, options?: grpc_1.CallOptions | grpc_1.requestCallback<Default>, callback?: grpc_1.requestCallback<Default>): grpc_1.ClientUnaryCall => {
            return super.SenderListen(message, metadata, options, callback);
        };
        SenderEvent: GrpcUnaryServiceInterface<SenderRequest, Default> = (message: SenderRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<Default>, options?: grpc_1.CallOptions | grpc_1.requestCallback<Default>, callback?: grpc_1.requestCallback<Default>): grpc_1.ClientUnaryCall => {
            return super.SenderEvent(message, metadata, options, callback);
        };
        SenderReply: GrpcUnaryServiceInterface<ReplyRequest, Default> = (message: ReplyRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<Default>, options?: grpc_1.CallOptions | grpc_1.requestCallback<Default>, callback?: grpc_1.requestCallback<Default>): grpc_1.ClientUnaryCall => {
            return super.SenderReply(message, metadata, options, callback);
        };
        SenderAction: GrpcUnaryServiceInterface<ReplyRequest, Default> = (message: ReplyRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<Default>, options?: grpc_1.CallOptions | grpc_1.requestCallback<Default>, callback?: grpc_1.requestCallback<Default>): grpc_1.ClientUnaryCall => {
            return super.SenderAction(message, metadata, options, callback);
        };
        AdapterRegist: GrpcChunkServiceInterface<AdapterRegistRequest, Default> = (metadata?: grpc_1.Metadata | grpc_1.CallOptions, options?: grpc_1.CallOptions): grpc_1.ClientDuplexStream<AdapterRegistRequest, Default> => {
            return super.AdapterRegist(metadata, options);
        };
        AdapterReceive: GrpcUnaryServiceInterface<AdapterRequest, Default> = (message: AdapterRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<Default>, options?: grpc_1.CallOptions | grpc_1.requestCallback<Default>, callback?: grpc_1.requestCallback<Default>): grpc_1.ClientUnaryCall => {
            return super.AdapterReceive(message, metadata, options, callback);
        };
        AdapterPush: GrpcUnaryServiceInterface<AdapterRequest, Default> = (message: AdapterRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<Default>, options?: grpc_1.CallOptions | grpc_1.requestCallback<Default>, callback?: grpc_1.requestCallback<Default>): grpc_1.ClientUnaryCall => {
            return super.AdapterPush(message, metadata, options, callback);
        };
        AdapterDestroy: GrpcUnaryServiceInterface<AdapterRequest, Empty> = (message: AdapterRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<Empty>, options?: grpc_1.CallOptions | grpc_1.requestCallback<Empty>, callback?: grpc_1.requestCallback<Empty>): grpc_1.ClientUnaryCall => {
            return super.AdapterDestroy(message, metadata, options, callback);
        };
        AdapterSender: GrpcUnaryServiceInterface<AdapterRequest, Default> = (message: AdapterRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<Default>, options?: grpc_1.CallOptions | grpc_1.requestCallback<Default>, callback?: grpc_1.requestCallback<Default>): grpc_1.ClientUnaryCall => {
            return super.AdapterSender(message, metadata, options, callback);
        };
    }
}
