package qq

import (
	"encoding/json"
	"fmt"
	"net/http"
	"reflect"
	"regexp"
	"strings"
	"sync"
	"time"

	"github.com/cdle/sillyGirl/core"
	"github.com/gin-gonic/gin"
	"github.com/gorilla/websocket"
)

var qq = core.NewBucket("qq")

type AutoGenerated struct {
	Action string `json:"action"`
	Echo   string `json:"echo"`
	Params struct {
		UserID  interface{} `json:"user_id"`
		Message string      `json:"message"`
	} `json:"params"`
}

type Message struct {
	Time int `json:"time"`
	// SelfID      int    `json:"self_id"`
	PostType    string `json:"post_type"`
	MessageType string `json:"message_type"`
	SubType     string `json:"sub_type"`
	MessageID   int    `json:"message_id"`
	UserID      int    `json:"user_id"`
	Message     string `json:"message"`
	RawMessage  string `json:"raw_message"`
	Sender      struct {
		Nickname string `json:"nickname"`
	}
}

func init() {
	core.Server.GET("/qq/receive", func(c *gin.Context) {
		var upGrader = websocket.Upgrader{
			CheckOrigin: func(r *http.Request) bool {
				return true
			},
		}
		ws, err := upGrader.Upgrade(c.Writer, c.Request, nil)
		if err != nil {
			c.Writer.Write([]byte(err.Error()))
			return
		}
		go func() {
			for {
				_, data, err := ws.ReadMessage()
				if err != nil {
					ws.Close()
					break
				}
				fmt.Println(string(data))
				msg := &Message{}
				json.Unmarshal(data, msg)
				if msg.PostType == "private" {
					// core.Senders <- &Sender{
					// 	Message: msg,
					// }
				}
				// fmt.Println("client message " + string(message))
				// err = ws.WriteMessage(mt, []byte(time.Now().String()))
				// if err != nil {
				// 	break
				// }
				// fmt.Println("system message " + time.Now().String())
			}
		}()

	})
}

type Sender struct {
	Message  *Message
	matches  [][]string
	Duration *time.Duration
	deleted  bool
	core.BaseSender
}

func (sender *Sender) GetContent() string {
	if sender.Content != "" {
		return sender.Content
	}
	text := ""
	text = strings.Replace(text, "amp;", "", -1)
	text = strings.Replace(text, "&#91;", "[", -1)
	text = strings.Replace(text, "&#93;", "]", -1)
	return strings.Trim(text, " ")
}

func (sender *Sender) GetUserID() string {

	return ""
}

func (sender *Sender) GetChatID() int {

	return 0
}

func (sender *Sender) GetImType() string {
	return "qq"
}

func (sender *Sender) GetMessageID() int {
	id := 0

	return id
}

func (sender *Sender) IsReply() bool {
	return false
}

func (sender *Sender) GetReplySenderUserID() int {
	return 0
}

func (sender *Sender) GetRawMessage() interface{} {
	return sender.Message
}

func (sender *Sender) IsAdmin() bool {
	var sid int64 = 0

	id := fmt.Sprint(sid)

	if id == qq.Get("bot_id") {
		return true
	}

	for _, v := range regexp.MustCompile(`\d+`).FindAllString(qq.Get("masters"), -1) {
		if id == v {
			return true
		}
	}
	return false
}

func (sender *Sender) IsMedia() bool {
	return false
}

var dd sync.Map

func (sender *Sender) Reply(msgs ...interface{}) (int, error) {

	return 0, nil
}

func (sender *Sender) Delete() error {

	return nil
}

func (sender *Sender) Disappear(lifetime ...time.Duration) {

}

func (sender *Sender) Finish() {

}

func (sender *Sender) Copy() core.Sender {
	new := reflect.Indirect(reflect.ValueOf(interface{}(sender))).Interface().(Sender)
	return &new
}

func (sender *Sender) GetUsername() string {

	return ""
}

func (sender *Sender) GetChatname() string {

	return ""
}
